---
galaxy_info:
  author: Red Hat
  description: |
    An Ansible role for generating custom RPMSs from upstream Gerrit changes in
    the TripleO project using DLRN. This repo then can be injected in the tested
    environment, a repo file created and a yum update should start using the
    built RPMs.
  license: Apache
  platforms:
    - name: CentOS
      versions:
        - 7
        - 8
    - name: EL
      versions:
        - 7
        - 8
  min_ansible_version: 2.8

dependencies:
  - extras-common
