---
## PLEASE READ ##
## Do not add tests to the skip list that are in    ##
## featureset016 - featureset019 w/o permission from ##
## the TripleO PTL, Thanks                          ##

known_failures:
  - test: 'mistral_tempest_tests.tests'
    reason: 'Skip Mistral tests as it needs to use mistral v2 endpoints'
  - test: 'ceilometer.tests.tempest.api.test_telemetry_notification_api.TelemetryNotificationAPITest'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'ceilometer.tests.tempest.api.test_telemetry_notification_api.TelemetryNotificationAdminAPITest'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'ceilometer.tests.tempest.scenario.test_object_storage_telemetry_middleware.TestObjectStorageTelemetry'
    reason: 'This telemetry installation is configured to use Gnocchi'
  - test: 'inspector_tempest_plugin.tests.test_basic.InspectorSmokeTest'
    reason: 'TODO(weshay) The service is not running on the overcloud, needs investigation'
  - test: 'tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON.test_implied_roles_create_check_show_delete'
    reason: 'Difference in Implied Roles check API return code'
    lp: 'https://bugs.launchpad.net/keystone/+bug/1660603'
  # skip list for undercloud
  - test: 'tempest.api.network.test_networks.NetworksTest.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips.FloatingIPTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_existent_host'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_remove_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates.AggregatesAdminTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_delete_server'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hosts.HostsAdminTestJSON.test_show_host_detail'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_simple_tenant_usage'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.floating_ips'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.images'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_external_networks_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_floating_ips_admin_actions'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_networks.NetworksIpV6Test.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_ports'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.security_groups.test_security_groups.SecurityGroupsTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_endpoints'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_roles'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_tags'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_roles_negative.RolesNegativeTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_services.ServicesTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_tenant_negative.TenantsNegativeTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_tenants.TenantsTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_tokens.TokensTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_users.UsersTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v2.test_users_negative.UsersNegativeTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_external_network_extension.ExternalNetworksTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_dhcp_ipv6.NetworksTestDHCPv6'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_ports.PortsIpV6TestJSON.test_port_list_filter_by_router_id'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_ports.PortsTestJSON.test_port_list_filter_by_router_id'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.v2.test_tenants.IdentityTenantsTest.test_list_tenants_returns_only_authorized_tenants'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.v2.test_users.IdentityUsersTest.test_user_update_own_password'
    reason: 'Running on undercloud'
    undercloud: true
