---
known_failures:
  - test: 'tempest.scenario.test_volume_boot_pattern'
    reason: 'rdo-manager tempest smoke test failing on "floating ip pool not found"'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1272289'
  - test: 'tempest.api.volume.test_volumes_get'
    reason: 'rdo-manager tempest smoke test failing on "floating ip pool not found"'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1272289'
  - test: 'tempest.api.identity.*v3'
    reason: 'Tempest Identify tests failed on V3 api on OSP-D puddle'
    bz: 'https://bugzilla.redhat.com/show_bug.cgi?id=1266947'
  - test: 'tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_cryptsetup'
    reason: 'TripleO does not deploy Barbican by default, which is needed for this test to pass'
  - test: 'tempest.scenario.test_encrypted_cinder_volumes.TestEncryptedCinderVolumes.test_encrypted_cinder_volumes_luks'
    reason: 'TripleO does not deploy Barbican by default, which is needed for this test to pass'
