---
## PLEASE READ ##
## Do not add tests to the skip list that are in    ##
## featureset016 - featureset019 w/o permission from ##
## the TripleO PTL, Thanks                          ##

known_failures:
  - test: 'neutron_tempest_plugin.scenario.test_dns_integration.DNSIntegrationTests'
    reason: 'Remove this blacklist when OVS 2.12 will be released and https://patchwork.ozlabs.org/patch/1102717/ merged.'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1832166'
  - test: 'neutron_tempest_plugin.api.test_revisions.TestRevisions.test_update_dns_domain_bumps_revision'
    reason: 'This test was enabled recently on ovn and we miss configuration in tripleo jobs, for sake of CI skipping them for now, but we will enabled them as fast as possible'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1832166'
  - test: 'neutron_tempest_plugin.scenario.test_internal_dns.InternalDNSTest.test_dns_domain_and_name'
    reason: 'This test was enabled recently on ovn and we miss configuration in tripleo jobs, for sake of CI skipping them for now, but we will enabled them as fast as possible'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1832166'
  - test: 'tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_port_security_macspoofing_port'
    reason: 'It can be removed when bug for OVN is repaired'
    lp: 'https://bugs.launchpad.net/tempest/+bug/1728886'
  - test: 'mistral_tempest_tests.tests.api.v2.test_actions.ActionTestsV2.test_get_list_actions_not_in_list_filter'
    reason: 'mismatch error, mistral team is investigating'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1736950'
  - test: 'patrole_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'zaqar_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'watcher_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'vitrage_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'trove_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'tripleo_common_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'tempest_horizon'
    reason: 'Not supported in TripleO'
  - test: 'octavia_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'murano_tempest_tests'
    reason: 'Not supported in TripleO'
  - test: 'mistral_tempest_tests'
    reason: 'Not supported in TripleO'
  - test: 'magnum_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'kuryr_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'heat_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'designate_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'congress_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'ec2api_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate'
    reason: 'Test is failing due microversion'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1821690'
  - test: 'neutron_tempest_plugin.api.test_ports'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_networks.NetworksTestJSON.test_create_update_network_dns_domain'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.admin.test_routers_ha'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.admin.test_l3_agent_scheduler'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_add_remove_network_from_dhcp_agent'
    reason: 'DHCP Agent is disabled by default in OVN'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1817705'
  - test: 'tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_networks_hosted_by_one_dhcp'
    reason: 'DHCP Agent is disabled by default in OVN'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1817705'
  - test: 'neutron_tempest_plugin.api.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_add_remove_network_from_dhcp_agent'
    reason: 'DHCP Agent is disabled by default in OVN'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1817705'
  - test: 'neutron_tempest_plugin.api.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_dhcp_port_status_active'
    reason: 'DHCP Agent is disabled by default in OVN'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1817705'
  - test: 'neutron_tempest_plugin.api.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_networks_hosted_by_one_dhcp'
    reason: 'DHCP Agent is disabled by default in OVN'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1817705'
  - test: 'neutron_tempest_plugin.scenario.test_qos.QoSTest.test_qos_basic_and_update'
    reason: 'Possible bug for QoS + FIP in OVN'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1817705'
  - test: 'barbican_tempest_plugin.tests.scenario.test_image_signing.ImageSigningSnapshotTest'
    reason: 'barbican and python-tempestconf not playing well'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1820668'
  - test: 'barbican_tempest_plugin.tests.scenario.test_image_signing.ImageSigningTest'
    reason: 'barbican and python-tempestconf not playing well'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1820671'
  - test: 'telemetry_tempest_plugin.scenario.test_telemetry_integration.TestTelemetryIntegration'
    reason: 'telemetry tests failed due to One or more ports have an IP allocation from this subnet'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1792862'
  - test: 'tempest.scenario.test_security_groups_basic_ops.TestSecurityGroupsBasicOps.test_cross_tenant_traffic'
    reason: 'Timed out waiting for 10.0.0.102 to become reachable from 10.0.0.117'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1856016'

  # skip list for undercloud
  - test: 'tempest.api.network.test_networks.NetworksTest.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips.FloatingIPTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_existent_host'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_remove_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates.AggregatesAdminTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_delete_server'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hosts.HostsAdminTestJSON.test_show_host_detail'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_simple_tenant_usage'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.floating_ips'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.images'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_external_networks_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_floating_ips_admin_actions'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_networks.NetworksIpV6Test.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_ports'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.security_groups.test_security_groups.SecurityGroupsTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON'
    reason: 'Running on undercloud'
    undercloud: true
