---
## PLEASE READ ##
## Do not add tests to the skip list that are in    ##
## featureset016 - featureset019 w/o permission from ##
## the TripleO PTL, Thanks                          ##

known_failures:
  - test: 'neutron_tempest_plugin.scenario'
    reason: 'Neutron Tempest plugin scenario tests are not yet stable.'
    lp: 'https://launchpad.net/bugs/1737940'
  - test: 'neutron_tempest_plugin.api.admin.test_shared_network_extension.RBACSharedNetworksTest'
    reason: 'RBAC policy resource conflict'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1753209'
  - test: 'patrole_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'zaqar_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'watcher_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'vitrage_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'trove_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'tripleo_common_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'tempest_horizon'
    reason: 'Not supported in TripleO'
  - test: 'octavia_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'murano_tempest_tests'
    reason: 'Not supported in TripleO'
  - test: 'mistral_tempest_tests'
    reason: 'Not supported in TripleO'
  - test: 'magnum_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'kuryr_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'ironic_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'heat_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'designate_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'congress_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'barbican_tempest_plugin'
    reason: 'Not supported in TripleO'
  - test: 'ec2api_tempest_plugin'
    reason: 'Not supported in TripleO/tempestconf'
  - test: 'neutron_tempest_plugin.api.test_trunk_negative'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_timestamp'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_subnetpools_negative'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_service_type_management'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_security_groups'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_routers_negative'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_routers'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_qos_negative'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_qos'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_ports'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_networks_negative'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_networks'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_floating_ips_negative'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_floating_ips'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_flavors_extensions'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_extension_driver_port_security'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_allowed_address_pair'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_address_scopes_negative'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.test_address_scopes'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.admin.test_shared_network_extension'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.admin.test_routers_ha'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.admin.test_networks.NetworksTestAdmin'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'neutron_tempest_plugin.api.admin.test_l3_agent_scheduler'
    reason: 'neutron tempest tests are failing by giving 503 Service Unavailable'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1793482'
  - test: 'tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate'
    reason: 'Test is failing due microversion'
    lp: 'https://bugs.launchpad.net/tripleo/+bug/1821690'
  - test: 'tempest.api.compute.servers.test_server_actions.ServerActionsTestJSON.test_resize_server_revert_with_volume_attached'
    reason: 'REVERT_RESIZE stuck for 300s: "VirtualInterfaceCreateException: Virtual Interface creation failed'
    lp: 'https://bugzilla.redhat.com/show_bug.cgi?id=1678681, https://bugs.launchpad.net/tripleo/+bug/1831223'
  - test: 'tempest.api.compute.servers.test_servers.ServerShowV263Test.test_show_update_rebuild_list_server'
    reason: 'ServerShowV263Test only passing when image has already been cached Edit'
    lp: 'https://bugs.launchpad.net/nova/+bug/1831866'
  # skip list for undercloud
  - test: 'tempest.api.network.test_networks.NetworksTest.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips.FloatingIPTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_existent_host'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_add_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates_negative.AggregatesAdminNegativeTestJSON.test_aggregate_remove_host_as_user'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_aggregates.AggregatesAdminTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_create_server.ServersWithSpecificFlavorTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hypervisor_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_delete_server'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_hosts.HostsAdminTestJSON.test_show_host_detail'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_simple_tenant_usage'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_servers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.floating_ips'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.admin.test_server_diagnostics_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.images'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_external_networks_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_floating_ips_admin_actions'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_routers_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_floating_ips_negative'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.test_networks.NetworksIpV6Test.test_external_network_visibility'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.network.admin.test_ports'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.compute.security_groups.test_security_groups.SecurityGroupsTestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON'
    reason: 'Running on undercloud'
    undercloud: true
  - test: 'vitrage_tempest_plugin'
    reason: 'Not supported in TripleO Undercloud'
    undercloud: true
