known_failures:
  - test: 'tempest.api.identity.admin.v3.test_roles.RolesV3TestJSON.test_implied_roles_create_check_show_delete'
    reason: 'Difference in Implied Roles check API return code'
    lp: 'https://bugs.launchpad.net/keystone/+bug/1660603'
  - test: 'neutron_tempest_plugin.scenario'
    reason: 'Neutron Tempest plugin scenario tests are not yet stable.'
    lp: 'https://launchpad.net/bugs/1737940'
