---
- name: gather facts used by role
  setup:
    gather_subset: "!min,distribution"
  when: ansible_distribution is not defined

- include: create-scripts.yml
  tags:
    - minion-scripts

- name: Run install via tripleo-operator-ansible
  when:
    - release in ['master']
    - step_install_minion|bool
  tags:
    - minion-install
  block:
    - name: Run dstat on the minion prior to minion install
      include_role:
        name: validate-perf
    - name: Install undercloud minion
      collections:
        - tripleo.operator
      import_role:
        name: tripleo-undercloud-minion-install
      vars:
        tripleo_undercloud_minion_install_debug: "{{ minion_minion_debug }}"

- name: Run legacy install
  when: release not in ['master']
  tags:
    - minion-install
  block:
    - include: install-minion.yml
