---
#  defaults file for modify-image

# These variable do not have a default because there is no sane default. The
# role will fail immediately if either is not specified.
# image_to_modify:
# modify_script:

# Run a specific command
# modify_image_run_command:

# Note: modify_image_run_command will run first then
# modify_image_upload_files will run. It is useful in case
# to make sure remote directories exists.
# The upload list of files
modify_image_upload_files: []

# The extract list defaults to empty list
modify_image_extract_list: []

# The package install list defaults to empty list
modify_image_install_packages: []

# By default we use the global working directory for modifying images
modify_image_working_dir: "{{ working_dir }}"

# ram, cpu and root password are not set by default to take libguestfs defaults by default
# modify_image_vc_ram:
# modify_image_vc_cpu:
# modify_image_vc_root_password:
modify_image_vc_verbose: false
modify_image_vc_trace: false
libguestfs_mode: true
# TODO(sshnaidm): implement initramfs image modifying
initramfs_image: false
