---
- name: Generate validate_edpm.sh script
  template:
    src: validate_edpm.sh.j2
    dest: "{{ working_dir }}/validate_external_compute.sh"
    mode: 0755

- name: Run deploy_compute.sh script
  shell: >
    set -o pipefail &&
    {{ working_dir }}/validate_external_compute.sh
    2>&1 {{ timestamper_cmd }} > {{ working_dir }}/validate_external_compute.log
