---

- name: Copy over disk size hint script template
  template:
    src: add-disk-size-hint.sh.j2
    dest: "{{ working_dir }}/add-disk-size-hint.sh"
    mode: 0755

- name: Rerun provision with disk size hints
  shell: >
    "{{ working_dir }}"/add-disk-size-hint.sh
  when: step_root_device_size


