# Generate a number of scripts from templates.  These are scripts
# rather than additional ansible tasks so that they can be run
# manually from the undercloud host.
- name: Create overcloud deploy script
  template:
    src: "{{ deploy_script }}"
    dest: "{{ working_dir }}/overcloud-deploy.sh"
    mode: 0755

- name: Create post-deploy script
  template:
    src: "{{ post_deploy_script }}"
    dest: "{{ working_dir }}/overcloud-deploy-post.sh"
    mode: 0755
