---
- name: Copy custom heat templates files if provided
  template:
    src: "{{ item.value.src }}"
    dest: "{{ upgrade_working_dir }}/{{ item.value.name }}"
  with_dict: "{{ upgrade_templates }}"

- name: Make sure no Tht repo is present
  file: path={{ upgrade_working_dir }}/{{ tht_dir }} state=absent

- name: Copy new Tht directory to the upgrade working dir
  shell: >
      cp -R /usr/share/openstack-tripleo-heat-templates \
      {{ upgrade_working_dir }}/{{ tht_dir }};

- name: Add the no ssh finger print checking into upgrade-non-controller.sh
  sudo: yes
  shell: >
      sed -i 's/ssh/ssh -o StrictHostKeyChecking=no/' \
      {{ upgrade_non_controller_script }}

- name: allow traffic for the controller
  shell: >
        sudo iptables -A BOOTSTACK_MASQ -s {{ network_isolation_ipv4_cidr }} ! \
        -d {{ network_isolation_ipv4_cidr }} -j MASQUERADE -t nat;
        sudo iptables-save > /etc/sysconfig/iptables;
  when: network_isolation

- name: Create overcloud upgrade script
  when: major_upgrade
  template:
    src: "{{ major_upgrade_script }}"
    dest: "{{ upgrade_working_dir }}/overcloud-upgrade.sh"
    mode: 0755

- name: Create overcloud upgrade script
  when: not major_upgrade
  template:
    src: "{{ minor_upgrade_script }}"
    dest: "{{ upgrade_working_dir }}/overcloud-upgrade.sh"
    mode: 0755