---
# tasks file for ansible-role-tripleo-tempest

- name: Create overcloud tempest setup script
  template:
    src: tempest-setup.j2
    dest: "{{ working_dir }}/tempest-setup.sh"
    mode: 0744

- name: Create tempest skipfile
  template:
    src: "{{ skip_file_src }}"
    dest: "{{ working_dir }}/{{ skip_file }}"
    mode: 0644
