- name: set network_args fact
  set_fact:
    network_args: >-
      -e {{overcloud_templates_path}}/environments/network-isolation.yaml
      -e {{overcloud_templates_path}}/environments/net-single-nic-with-vlans.yaml
      -e $HOME/network-environment.yaml
  when: network_isolation

- name: enable pacemaker
  set_fact:
    pacemaker_args: >-
      -e {{overcloud_templates_path}}/environments/puppet-pacemaker.yaml
  when: enable_pacemaker

- name: disable L3 HA
  set_fact:
    pacemaker_args: >-
      {{ pacemaker_args }}
      -e $HOME/neutronl3ha.yaml
  when: enable_pacemaker and overcloud_nodes|length < 3

- name: set workers_args fact
  set_fact:
    workers_args: >-
      -e {{overcloud_templates_path}}/environments/low-memory-usage.yaml
  when: release not in ['mitaka', 'liberty']

- name: Use KVM for Red Hat distro
  set_fact: libvirt_args="--libvirt-type kvm"
  when: ansible_distribution == 'RedHat'
