---
- name: Create the tripleo-ui simple validate script
  template:
    src: "{{ ui_validate_simple_script }}"
    dest: "{{ local_working_dir }}/ui_validate_simple.sh"
    mode: 0744

- name: Execute the simple tripleo-ui validation
  shell: >
    set -o pipefail &&
    {{ local_working_dir }}/ui_validate_simple.sh
    | tee {{ ui_validate_simple_log }}
  changed_when: true
