---
# The following two tasks turn a standalone
# deployment into a single purpose job
# setup repos and test for repoclosure.

# execute and log repoclosure
# stops execution when failed: if zuul.repoclosure
# or repoclosure is defined
# if this passes continue
- name: register enabled yum repos
  shell: dnf repolist | awk '{print $1}'
  register: yum_repos
  changed_when: true

- name: debug register yum_repos
  debug:
    var: yum_repos.stdout_lines

- name: Create repoclosure script
  template:
    src: "{{ repoclosure_script_source }}"
    dest: "{{ repo_setup_dir }}/{{ repoclosure_script }}"
    mode: 0755
  changed_when: true

- name: Execute repoclosure to ensure rpms are installable
  shell: >
    set -o pipefail &&
    {{ repo_setup_dir }}/{{ repoclosure_script }} 2>&1 {{ timestamper_cmd }}
    | tee -a {{ repo_setup_dir }}/{{ repoclosure_log }}
  become: true
  no_log: result.rc == 0
  changed_when: result.rc == 0
