---

overcloud_working_dir: /home/heat-admin

environment_file: environment.j2
apply_workarounds: false
workarounds_script: workarounds.sh.j2

floating_ip_cidr: "{{ undercloud_network_cidr|default('192.0.2.0/24') }}"
floating_ip_start: "{{ floating_ip_cidr|nthhost(100) }}"
floating_ip_end: "{{ floating_ip_cidr|nthhost(120) }}"
external_network_gateway: "{{ floating_ip_cidr|nthhost(1) }}"
