---
release: newton

node:
    prefix:
        - "{{ 1000 |random }}"
        - "{{ lookup('env', 'USER') }}"
        - "{{ lookup('env', 'BUILD_NUMBER') }}"
tmp:
    node_prefix: '{{ node.prefix | reject("none") | join("-") }}-'

os_username: admin
os_password: password
os_tenant_name: admin
os_auth_url: 'http://10.0.1.10:5000/v2.0'
cloud_name: qeos7

stack_name: 'oooq-{{ prefix }}stack'
rc_file: /home/{{ ansible_user }}/overcloudrc
node_name: 'undercloud'
ssh_extra_args: '-F "{{ local_working_dir }}/ssh.config.ansible"'
undercloud_key: "{{ local_working_dir }}/id_rsa_undercloud"
node_groups:
    - 'undercloud'
    - 'tester'
templates_dir: "{{ local_working_dir }}/openstack-virtual-baremetal/templates"
ovb_dir: "{{ local_working_dir }}/openstack-virtual-baremetal"
heat_template: "{{ templates_dir }}/quintupleo.yaml"
environment_list:
    - "{{ templates_dir }}/resource-registry.yaml"
    - "{{ local_working_dir }}/{{ prefix }}env.yaml"

latest_guest_image:
    mitaka: CentOS-7-x86_64-GenericCloud-released-latest
    newton: CentOS-7-x86_64-GenericCloud-released-latest
    ocata: CentOS-7-x86_64-GenericCloud-released-latest
    master: CentOS-7-x86_64-GenericCloud-released-latest
    rhos-8: rhel-7.3-server-x86_64-latest
    rhos-9: rhel-7.3-server-x86_64-latest
    rhos-10: rhel-7.3-server-x86_64-latest

existing_key_location: '{{ local_working_dir }}'
remove_image_from_host_cloud: false

bmc_flavor: m1.medium
bmc_image: 'bmc-base'
bmc_prefix: '{{ prefix }}bmc'

baremetal_flavor: m1.large
baremetal_image: 'ipxe-boot'
baremetal_prefix: '{{ prefix }}baremetal'

key_name: '{{ prefix }}key'
private_net: '{{ prefix }}private'
node_count: 2
public_net: '{{ prefix }}public'
provision_net: '{{ prefix }}provision'

# QuintupleO-specific params ignored by virtual-baremetal.yaml
undercloud_name: '{{ prefix }}undercloud'
undercloud_image: '{{ prefix }}undercloud.qcow2'
undercloud_flavor: m1.xlarge
external_net:  '10.2.1.0/22'

network_isolation_type: multiple-nics

registered_releases:
  - mitaka
  - newton
  - ocata
  - master
  - rhos-8
  - rhos-9
  - rhos-10

