---
release: master
ovb_repo_version: a3786bca1604d6048562af80eca3bcad119e5065

node:
    prefix:
        - "{{ 1000 |random }}"
        - "{{ lookup('env', 'USER') }}"
        - "{{ lookup('env', 'BUILD_NUMBER') }}"
tmp:
    node_prefix: '{{ node.prefix | reject("none") | join("-") }}-'

os_username: admin
os_password: password
os_tenant_name: admin
os_auth_url: 'http://10.0.1.10:5000/v2.0'
os_region_name: 'regionOne'
cloud_name: qeos7

stack_name: 'oooq-{{ prefix }}stack'
rc_file: /home/{{ ansible_user }}/overcloudrc
node_name: 'undercloud'
ssh_extra_args: '-F "{{ local_working_dir }}/ssh.config.ansible"'
undercloud_key: "{{ local_working_dir }}/id_rsa_undercloud"
nodepool_user: 'zuul'
node_groups:
    - 'undercloud'
    - 'tester'
templates_dir: "{{ local_working_dir }}/openstack-virtual-baremetal/templates"
ovb_dir: "{{ local_working_dir }}/openstack-virtual-baremetal"
heat_template: "{{ templates_dir }}/quintupleo.yaml"
environment_list:
    - "{{ templates_dir }}/resource-registry.yaml"
    - "{{ local_working_dir }}/{{ prefix }}env.yaml"
boot_from_volume: false
baremetal_boot_from_volume_size: 50
undercloud_boot_from_volume_size: 50

latest_guest_image:
    mitaka: CentOS-7-x86_64-GenericCloud-released-latest
    newton: CentOS-7-x86_64-GenericCloud-released-latest
    ocata: CentOS-7-x86_64-GenericCloud-released-latest
    master: CentOS-7-x86_64-GenericCloud-released-latest
    rhos-9: rhel-7.4-server-x86_64-latest
    rhos-10: rhel-7.4-server-x86_64-latest
    rhos-11: rhel-7.4-server-x86_64-latest

port_security: true

baremetal_ports_template:
    multiple-nics: baremetal-ports-all.yaml
    multi-nic: baremetal-ports-all.yaml
    public-bond: baremetal-ports-public-bond.yaml

baremetal_port_security_template:
    none: baremetal-ports-default-port-security.yaml
    multiple-nics: baremetal-ports-all-port-security.yaml
    multi-nic: baremetal-ports-all-port-security.yaml
    public-bond: baremetal-ports-public-bond-port-security.yaml

existing_key_location: '~/.ssh/id_rsa'
remove_image_from_host_cloud: false

bmc_flavor: m1.medium
bmc_image: 'bmc-base'
bmc_prefix: '{{ prefix }}bmc'

baremetal_flavor: m1.large
baremetal_image: 'ipxe-boot'
baremetal_prefix: '{{ prefix }}baremetal'

key_name: '{{ prefix }}key'
private_net: '{{ prefix }}private'
node_count: 2
public_net: '{{ prefix }}public'
provision_net: '{{ prefix }}provision'
provision_net_cidr: 192.0.2.0/24

# QuintupleO-specific params ignored by virtual-baremetal.yaml
undercloud_name: '{{ prefix }}undercloud'
undercloud_image: '{{ prefix }}undercloud.qcow2'
undercloud_flavor: m1.xlarge
external_net:  '10.2.1.0/22'

network_isolation_type: multiple-nics

registered_releases:
  - newton
  - ocata
  - pike
  - master
  - rhos-11
  - rhos-12

baremetal_driver: >-
    {% if release not in ['newton', 'ocata', 'pike'] -%}
    "ipmi"
    {%- else -%}
    "pxe_ipmitool"
    {%- endif -%}

# OVB environment clean up
cleanup_stacks_keypairs: false
cleanup_stacks_keypairs_script: cleanup-stacks-keypairs.sh.j2
cleanup_stacks_keypairs_log: "{{ local_working_dir }}/cleanup_stacks_keypairs.log"
