---
- name: copy both public and private ssh keys to root directory
  become: yes
  copy:
      src: "{{ lookup('env','HOME') }}/.ssh/{{ item }}"
      dest: "/root/.ssh/{{ item }}"
      mode: 0600
  with_items:
      - id_rsa
      - id_rsa.pub

- name: Copy instackenv.json to undercloud
  copy:
    src="{{ local_working_dir }}/nodes.json"
    dest="{{ working_dir }}/instackenv.json"

- name: Copy over setup undercloud connectivity script template
  template:
      src: setup-undercloud-connectivity.sh.j2
      dest: "{{ working_dir }}/setup-undercloud-connectivity.sh"
      mode: 0755

- name: Setup interfaces, connectivity on the undercloud
  become: yes
  shell: >
      "{{ working_dir }}"/setup-undercloud-connectivity.sh > \
       {{ setup_undercloud_connectivity_log }} 2>&1

