---
# tasks file for baremetal-undercloud's packages subrole

# Install the Tripleo package (usually python-tripleoclient)
- name: Install TripleO package
  become: true
  package:
    name: "{{ undercloud_rpm_dependencies }}"
    state: present
  tags:
    - undercloud-tripleo-pkg

# Install additional packages (if declared)
- name: Install additional packages
  become: true
  package:
    name: "{{ undercloud_additional_pkgs|default([]) }}"
    state: present
  tags:
    - undercloud-additional-pkgs

# Configure ntp on undercloud
- include: ntp.yml
  become: true
  when: "{{ step_undercloud_ntp|bool }}"
  tags:
    - undercloud-ntp
