---

tripleo_common_dir: /usr/share/openstack-tripleo-common
containerized_overcloud: false
overcloud_prep_containers_script: overcloud-prep-containers.sh.j2
overcloud_prep_containers_log: overcloud_prep_containers.log
# Be careful with this setting as it entirely wipes the /var/lib/docker directory
# Useful in CI to workaround disk space issue
# https://bugs.launchpad.net/tripleo/+bug/1694709
delete_docker_cache: false
prepare_service_env_args: -e {{ overcloud_templates_path }}/environments/docker.yaml
