---

tripleo_common_dir: /usr/share/openstack-tripleo-common
containerized_overcloud: false
overcloud_prep_containers_script: overcloud-prep-containers.sh.j2
containers_default_parameters: container-default-parameters.yaml.j2
overcloud_prep_containers_log: overcloud_prep_containers.log
ctl_plane_ip: "{{undercloud_network_gateway|default(undercloud_network_cidr|nthhost(1))}}"
containers_compute_dns_server: 8.8.8.8
