---
standalone_config: standalone_config.yaml.j2
standalone_network: 192.168.24
standalone_network_prefix: 24
standalone_ip: 192.168.24.1
standalone_ha_control_virtual_ip: 192.168.24.3
standalone_interface: br-ex
standalone_neutron_bridge_mappings: "datacentre:br-ctlplane,tenant:br-tenant"
standalone_neutron_physical_bridge: br-ctlplane

# container prep script
standalone_container_prep_options: ''
standalone_container_prep_script: standalone-container-prep.sh.j2
standalone_container_prep_log: standalone_container_prep_upgrade.log

# Upgrade script
standalone_upgrade_script: standalone.sh.j2
standalone_upgrade_log: standalone_upgrade.log

# deployment role
standalone_role: Standalone.yaml

standalone_selinux_mode: permissive

standalone_libvirt_type: kvm

standalone_container_cli: docker

standalone_custom_env_files: []
standalone_hostname: standalone.localdomain
