---
nodepool_cirros_url: http://download.cirros-cloud.net/0.3.6/cirros-0.3.6-x86_64-disk.img
nodepool_cirros_dest: /opt/cache/files/cirros-0.3.6-x86_64-disk.img
nodepool_cirros_checksum: md5:d56d54f110654dfd29b0e8ed56e6cda8
repos:
  - https://opendev.org/openstack/tripleo-quickstart
  - https://opendev.org/openstack/tripleo-quickstart-extras
  - https://opendev.org/openstack/tripleo-upgrade
  - https://opendev.org/x/browbeat
  - https://opendev.org/openstack/tripleo-ha-utils
  - https://opendev.org/openstack/tripleo-ci
  - https://opendev.org/openstack/devstack
  - https://opendev.org/openstack/devstack-gate
  - https://opendev.org/openstack/openstack-ansible-os_tempest
  - https://opendev.org/openstack/ansible-config_template
  - https://opendev.org/openstack/ansible-role-python_venv_build
zuul_changes: "{{ lookup('env', 'ZUUL_CHANGES') }}"
subnode_swap_size: 8388608  # 8GB
update_subnodes: true
rdo_cloud_provider: true
packages_list:
  - git
  - unbound
  - screen
  - vim
  - curl
  - iptables-services
