---
nodepool_cirros_url: http://download.cirros-cloud.net/0.3.6/cirros-0.3.6-x86_64-disk.img
nodepool_cirros_dest: /opt/cache/files/cirros-0.3.6-x86_64-disk.img
nodepool_cirros_checksum: md5:a30f156a83471adf89ebb70dc96d0c82
repos:
  - https://git.openstack.org/openstack/tripleo-quickstart
  - https://git.openstack.org/openstack/tripleo-quickstart-extras
  - https://git.openstack.org/openstack/tripleo-upgrade
  - https://git.openstack.org/openstack/browbeat
  - https://git.openstack.org/openstack/tripleo-ha-utils
  - https://git.openstack.org/openstack-infra/tripleo-ci
  - https://git.openstack.org/openstack-dev/devstack
  - https://git.openstack.org/openstack-infra/devstack-gate
  - https://git.openstack.org/openstack/openstack-ansible-os_tempest
  - https://git.openstack.org/openstack/ansible-config_template
  - https://git.openstack.org/openstack/ansible-role-python_venv_build
zuul_changes: "{{ lookup('env', 'ZUUL_CHANGES') }}"
subnode_swap_size: 8388608  # 8GB
update_subnodes: true
rdo_cloud_provider: true
packages_list:
  - git
  - unbound
  - screen
  - vim
  - wget
  - iptables-services
