---
reproducer_zuul_based_quickstart_script: reproducer-zuul-based-quickstart.sh.j2
reproducer_fresh_box_setup_script: reproducer-fresh-box-setup.sh.j2
reproducer_zuul_based_quickstart_readme_file: "{{ artcl_collect_dir }}/README-reproducer.html"
reproducer_zuul_based_launcher_playbook: launcher-playbook.yaml.j2
launcher_env_setup_playbook: launcher-env-setup-playbook.yaml.j2
zuul_reproducer_dir: reproducer-quickstart
mirror_path: mirror.regionone.rdo-cloud.rdoproject.org
