---

artcl_collect: true
artcl_collect_list:
  - /var/lib/heat-config/
  - /var/lib/kolla/config_files
  - /var/lib/oooq-images/*/*.log
  - /var/lib/oooq-images/*/*.sh
  - /var/lib/pacemaker/cib/cib*
  - /var/lib/pacemaker/pengine/pe-input*
  - /var/log/dmesg.txt
  - /var/log/host_info.txt
  - /var/log/journal.txt
  - /var/log/postci.txt
  - /var/log/secure
  - /var/log/bootstrap-subnodes.log
  - /var/log/unbound.log
  - /var/log/yum.log
  - /var/log/aodh/
  - /var/log/audit/
  - /var/log/barbican/
  - /var/log/ceilometer/
  - /var/log/ceph/
  - /var/log/cinder/
  - /var/log/cloudkitty/
  - /var/log/cluster/
  - /var/log/config-data/
  - /var/log/congress/
  - /var/log/containers/
  - /var/log/deployed-server-enable-ssh-admin.log
  - /var/log/deployed-server-os-collect-config.log
  - /var/log/designate/
  - /var/log/dmesg/
  - /var/log/extra/
  - /var/log/ec2api/
  - /var/log/glance/
  - /var/log/gnocchi/
  - /var/log/heat/
  - /var/log/heat-launcher/
  - /var/log/horizon/
  - /var/log/httpd/
  - /var/log/ironic/
  - /var/log/ironic-inspector/
  - /var/log/libvirt/
  - /var/log/keystone/
  - /var/log/manila/
  - /var/log/mariadb/
  - /var/log/mistral/
  - /var/log/monasca/
  - /var/log/murano/
  - /var/log/neutron/
  - /var/log/nova/
  - /var/log/novajoin/
  - /var/log/octavia/
  - /var/log/openvswitch/
  - /var/log/ovn/
  - /var/log/pacemaker/
  - /var/log/panko/
  - /var/log/qdr/
  - /var/log/rabbitmq/
  - /var/log/redis/
  - /var/log/sahara/
  - /var/log/sensu/
  - /var/log/swift/
  - /var/log/tacker/
  - /var/log/tempest/
  - /var/log/trove/
  - /var/log/tripleo-container-image-prepare.log
  - /var/log/vitrage/
  - /var/log/watcher/
  - /var/log/zaqar/
  - /var/tmp/sosreport*
  - /etc/
  - /home/*/.instack/install-undercloud.log
  - /home/*/stackrc
  - /home/*/overcloudrc*
  - /home/*/*.log
  - /home/*/*.json
  - /home/*/*.conf
  - /home/*/*.yml
  - /home/*/*.yaml
  - /home/*/*.sh
  - /home/*/*.rst
  - /home/*/*.pem
  - /home/*/deploy-overcloudrc
  - /home/*/network-environment.yaml
  - /home/*/skip_file
  - /home/*/*.subunit
  - /home/*/tempest/*.xml
  - /home/*/tempest/*.html
  - /home/*/tempest/*.log
  - /home/*/tempest/etc/*.conf
  - /home/*/tempest/*.subunit
  - /home/*/tempest/*.json
  - /home/*/tripleo-heat-installer-templates/
  - /home/*/local_tht/
  - /home/*/gating_repo.tar.gz
  - /home/*/browbeat/
  - /usr/share/openstack-tripleo-heat-templates/
  - /home/*/tripleo-heat-templates/
  - /tmp/tripleoclient*
  # The next 2 items are temporary until config-download is executed
  # from a Mistral workflow (WIP in Queens)
  - /home/*/inventory
  - /home/*/tripleo-config-download/
artcl_exclude_list:
  - /etc/udev/hwdb.bin
  - /etc/puppet/modules
  - /etc/project-config
  - /etc/services
  - /etc/selinux/targeted
  - /etc/pki/ca-trust/extracted
  - /etc/alternatives
  - /var/log/journal
# artcl_collect_dir is defaulted in extras-common
artcl_gzip_only: true
artcl_tar_gz: false

## publishing related vars
artcl_publish: false
artcl_env: default
artcl_readme_file: "{{ artcl_collect_dir }}/README-logs.html"
artcl_txt_rename: false
# give up log upload after 30 minutes
artcl_publish_timeout: 1800
artcl_artifact_url: "file://{{ local_working_dir }}"
artcl_full_artifact_url: "{{ artcl_artifact_url }}/{{ lookup('env', 'BUILD_TAG') }}/"
artcl_use_rsync: false
artcl_rsync_use_daemon: false

artcl_use_swift: false
# clean up the logs after 31 days
artcl_swift_delete_after: 2678400
artcl_swift_container: logs
artcl_use_zuul_swift_upload: false
artcl_zuul_swift_upload_path: /usr/local/bin

artcl_collect_sosreport: false
artcl_sosreport_options: "--batch"

## Doc generation specific vars
artcl_gen_docs: false
artcl_create_docs_payload:
    included_deployment_scripts: []
    included_static_docs: []
    table_of_contents: []
artcl_docs_source_dir: "{{ local_working_dir }}/usr/local/share/ansible/roles/collect-logs/docs/source"
artcl_docs_build_dir: "{{ artcl_collect_dir }}/docs/build"
artcl_verify_sphinx_build: false
artcl_logstash_files:
  - /home/*/deployed_server_prepare.txt
  - /home/*/docker_journalctl.log
  - /home/*/failed_deployment_list.log
  - /home/*/hostname.sh.log
  - /home/*/install_built_repo.log
  - /home/*/install_packages.sh.log
  - /home/*/install-undercloud.log
  - /home/*/ironic-python-agent.log
  - /home/*/nova_actions_check.log
  - /home/*/overcloud_create_ssl_cert.log
  - /home/*/overcloud_custom_tht_script.log
  - /home/*/overcloud_delete.log
  - /home/*/overcloud_deploy.log
  - /home/*/overcloud_deploy_post.log
  - /home/*/overcloud_failed_prepare_resources.log
  - /home/*/overcloud-full.log
  - /home/*/overcloud_image_build.log
  - /home/*/overcloud_prep_containers.log
  - /home/*/overcloud_prep_images.log
  - /home/*/overcloud_prep_network.log
  - /home/*/overcloud_validate.log
  - /home/*/*upgrade*.log
  - /home/*/*update*.log
  - /home/*/repo_setup.log
  - /home/*/repo_setup.sh.*.log
  - /home/*/undercloud_install.log
  - /home/*/undercloud_reinstall.log
  - /home/*/undercloud_custom_tht_script.log
  - /home/*/upgrade-undercloud-repo.sh.log
  - /home/*/validate-overcloud-ipmi-connection.log
  - /home/*/vxlan_networking.sh.log
  - /home/*/workload_launch.log
  - /home/*/yum_mirror_error.log
  - /home/*/yum_mirror.log
  - /home/*/tempest_output.log
  - /var/log/bootstrap-subnodes.log
  - /var/log/tripleo-container-image-prepare.log
#ara_graphite_server: graphite.tripleo.org
ara_graphite_prefix: "tripleo.{{ lookup('env', 'STABLE_RELEASE')|default('master', true) }}.{{ lookup('env', 'TOCI_JOBTYPE') }}."
ara_only_successful_tasks: true
ara_tasks_map:
  "overcloud-deploy : Deploy the overcloud": overcloud.deploy.seconds
  "undercloud-deploy : Install the undercloud": undercloud.install.seconds
  "build-images : run the image build script (direct)": overcloud.images.seconds
  "overcloud-prep-images : Prepare the overcloud images for deploy": prepare_images.seconds
  "validate-simple : Validate the overcloud": overcloud.ping_test.seconds
  "validate-tempest : Execute tempest": overcloud.tempest.seconds
# InfluxDB module settings
influxdb_only_successful_tasks: true
influxdb_measurement: test
# influxdb_url:
influxdb_port: 8086
influxdb_user:
influxdb_password:
influxdb_dbname: testdb
influxdb_data_file_path: "{{ lookup('env', 'LOCAL_WORKING_DIR')|default('/tmp', true) }}/influxdb_data"
influxdb_create_data_file: true
odl_extra_log_dir: /var/log/extra/odl
odl_extra_info_log: "{{ odl_extra_log_dir }}/odl_info.log"
ara_overcloud_db_path: "/var/lib/mistral/overcloud/ara_overcloud.sqlite"
