---

artcl_collect: true
artcl_collect_list:
  - /var/log/
  - /var/lib/pacemaker/cib/cib*
  - /var/lib/heat-config/heat-config-puppet/
  - /var/lib/heat-config/heat-config-script/
  - /var/tmp/sosreport*
  - /var/lib/oooq-images/*/*.sh
  - /var/lib/oooq-images/*/*.log
  - /etc/
  - /home/*/.instack/install-undercloud.log
  - /home/*/stackrc
  - /home/*/overcloudrc*
  - /home/*/*.log
  - /home/*/*.json
  - /home/*/*.conf
  - /home/*/*.yml
  - /home/*/*.yaml
  - /home/*/*.sh
  - /home/*/*.rst
  - /home/*/*.pem
  - /home/*/deploy-overcloudrc
  - /home/*/network-environment.yaml
  - /home/*/skip_file
  - /home/*/*.subunit
  - /home/*/tempest/*.xml
  - /home/*/tempest/*.html
  - /home/*/tempest/*.log
  - /home/*/tempest/etc/*.conf
  - /home/*/tempest/*.subunit
  - /home/*/tempest/*.json
  - /home/*/local_tht/
  - /home/*/gating_repo.tar.gz
  - /home/*/browbeat/ansible/bug_report.log
  - /home/*/browbeat/results/
  - /usr/share/openstack-tripleo-heat-templates/
  - /tmp/tripleoclient*
  # The next 2 items are temporary until config-download is executed
  # from a Mistral workflow (WIP in Queens)
  - /home/*/inventory
  - /home/*/tripleo-config-download/
artcl_exclude_list:
  - /etc/udev/hwdb.bin
  - /etc/puppet/modules
  - /etc/project-config
  - /etc/services
  - /etc/selinux/targeted
  - /etc/pki/ca-trust/extracted
  - /etc/alternatives
  - /var/log/journal
# artcl_collect_dir is defaulted in extras-common
artcl_gzip_only: true
artcl_tar_gz: false

## publishing related vars
artcl_publish: false
artcl_env: default
artcl_readme_file: "{{ artcl_collect_dir }}/README-logs.html"
artcl_txt_rename: false
# give up log upload after 30 minutes
artcl_publish_timeout: 1800
artcl_artifact_url: "file://{{ local_working_dir }}"
artcl_full_artifact_url: "{{ artcl_artifact_url }}/{{ lookup('env', 'BUILD_TAG') }}/"
artcl_use_rsync: false
artcl_rsync_use_daemon: false

artcl_use_swift: false
# clean up the logs after 31 days
artcl_swift_delete_after: 2678400
artcl_swift_container: logs
artcl_use_zuul_swift_upload: false
artcl_zuul_swift_upload_path: /usr/local/bin

artcl_collect_sosreport: false
artcl_sosreport_options: "--batch"

## Doc generation specific vars
artcl_gen_docs: false
artcl_create_docs_payload:
    included_deployment_scripts: []
    included_static_docs: []
    table_of_contents: []
artcl_docs_source_dir: "{{ local_working_dir }}/usr/local/share/ansible/roles/collect-logs/docs/source"
artcl_docs_build_dir: "{{ artcl_collect_dir }}/docs/build"
artcl_verify_sphinx_build: false
artcl_logstash_files:
  - /home/*/deployed_server_prepare.txt
  - /home/*/docker_journalctl.log
  - /home/*/failed_deployment_list.log
  - /home/*/hostname.sh.log
  - /home/*/install_built_repo.log
  - /home/*/install_packages.sh.log
  - /home/*/ironic-python-agent.log
  - /home/*/overcloud_create_ssl_cert.log
  - /home/*/overcloud_custom_tht_script.log
  - /home/*/overcloud_delete.log
  - /home/*/overcloud_deploy.log
  - /home/*/overcloud_deploy_post.log
  - /home/*/overcloud-full.log
  - /home/*/overcloud_image_build.log
  - /home/*/overcloud_prep_containers.log
  - /home/*/overcloud_prep_images.log
  - /home/*/overcloud_prep_network.log
  - /home/*/overcloud_upgrade_console.log
  - /home/*/overcloud_validate.log
  - /home/*/repo_setup.log
  - /home/*/repo_setup.sh.*.log
  - /home/*/undercloud_install.log
  - /home/*/undercloud_reinstall.log
  - /home/*/upgrade-undercloud-repo.sh.log
  - /home/*/validate-overcloud-ipmi-connection.log
  - /home/*/vxlan_networking.sh.log
  - /home/*/yum_mirror_error.log
  - /home/*/yum_mirror.log
  - /home/*/tempest_output.log
  - /var/log/bootstrap-subnodes.log
#ara_graphite_server: graphite.tripleo.org
ara_graphite_prefix: "tripleo.{{ lookup('env', 'STABLE_RELEASE')|default('master', true) }}.{{ lookup('env', 'TOCI_JOBTYPE') }}."
ara_only_successful_tasks: true
ara_tasks_map:
  "overcloud-deploy : Deploy the overcloud": overcloud.deploy.seconds
  "undercloud-deploy : Install the undercloud": undercloud.install.seconds
  "build-images : run the image build script (direct)": overcloud.images.seconds
  "overcloud-prep-images : Prepare the overcloud images for deploy": prepare_images.seconds
  "validate-simple : Validate the overcloud": overcloud.ping_test.seconds
  "validate-tempest : Execute tempest": overcloud.tempest.seconds
