---

artcl_collect: true
artcl_collect_list:
  - /var/log/
  - /var/lib/pacemaker/cib/cib*
  - /var/lib/heat-config/heat-config-puppet/
  - /var/lib/heat-config/heat-config-script/
  - /var/tmp/sosreport*
  - /etc/
  - /home/*/.instack/install-undercloud.log
  - /home/*/stackrc
  - /home/*/overcloudrc
  - /home/*/*.log
  - /home/*/*.json
  - /home/*/*.conf
  - /home/*/*.yml
  - /home/*/*.yaml
  - /home/*/*.sh
  - /home/*/*.rst
  - /home/*/*.pem
  - /home/*/deploy-overcloudrc
  - /home/*/network-environment.yaml
  - /home/*/skip_file
  - /home/*/*.subunit
  - /home/*/tempest/*.xml
  - /home/*/tempest/*.html
  - /home/*/tempest/*.log
  - /home/*/tempest/etc/*.conf
  - /home/*/tempest/*.subunit
  - /home/*/local_tht/
  - /home/*/gating_repo.tar.gz
  - /home/*/browbeat/ansible/bug_report.log
  - /home/*/browbeat/results/
  - /usr/share/openstack-tripleo-heat-templates/
  - /tmp/tripleoclient*
artcl_exclude_list:
  - /etc/udev/hwdb.bin
  - /etc/puppet/modules
  - /etc/project-config
  - /etc/services
  - /etc/selinux/targeted
  - /etc/pki/ca-trust/extracted
  - /etc/alternatives
  - /var/log/journal
artcl_collect_dir: "{{ local_working_dir }}/collected_files"
artcl_gzip_only: true
artcl_tar_gz: false

## publishing related vars
artcl_publish: false
artcl_env: default
artcl_readme_file: "{{ artcl_collect_dir }}/README-logs.html"
artcl_txt_rename: false
# give up log upload after 30 minutes
artcl_publish_timeout: 1800
artcl_artifact_url: "file://{{ lookup('env', 'PWD') }}"
artcl_full_artifact_url: "{{ artcl_artifact_url }}/{{ lookup('env', 'BUILD_TAG') }}/"
artcl_use_rsync: false
artcl_rsync_use_daemon: false

artcl_use_swift: false
# clean up the logs after 31 days
artcl_swift_delete_after: 2678400
artcl_swift_container: logs
artcl_use_zuul_swift_upload: false
artcl_zuul_swift_upload_path: /usr/local/bin

artcl_collect_sosreport: false

## Doc generation specific vars
artcl_gen_docs: false
artcl_create_docs_payload:
    included_deployment_scripts: []
    included_static_docs: []
    table_of_contents: []
artcl_docs_source_dir: "{{ local_working_dir }}/usr/local/share/ansible/roles/collect-logs/docs/source"
artcl_docs_build_dir: "{{ artcl_collect_dir }}/docs/build"
artcl_verify_sphinx_build: false
