---
- name: Fetch tripleo containers
  command: cat "{{ container_file }}"
  register: all_containers
  changed_when: false

- name: Store tripleo containers
  set_fact:
    containers: "{{ all_containers.stdout | from_yaml }}"

- name: Filter out non-tripleo containers
  set_fact:
    non_tripleo_containers: "{{ containers.container_images | json_query('[?image_source != `tripleo`]') }}"

- name: Filter out non-tripleo containers excluding kolla image_source
  set_fact:
    non_tripleo_containers: "{{ non_tripleo_containers | json_query('[?image_source != `kolla`]') }}"
  when: release in ["train"]

- name: Store non-tripleo containers
  set_fact:
    non_tripleo_containers: "{{ non_tripleo_containers | map(attribute='imagename') | list }}"

- name: Print non-tripleo containers
  debug:
    msg: "{{ non_tripleo_containers }}"

- name: "Pull containers from {{ docker_registry_host }}"
  become: true
  command: 'podman pull {{ item }}'
  register: pull_success
  changed_when: false
  loop: "{{ non_tripleo_containers }}"

- name: List down missing containers
  set_fact:
    missing_containers: "{{ missing_containers | default([]) + [item] }}"
  when:
    - item.rc != 0
    - pull_success is defined
  loop: "{{ pull_success.results }}"

- name: Pull failed containers from RDO registry
  become: true
  command: "podman pull docker://trunk.registry.rdoproject.org/ceph//{{ item.split('/')[-1] }}"
  register: rdo_pull_success
  loop: "{{ missing_containers }}"
  changed_when: false
  when:
    - missing_containers is defined
    - missing_containers | len > 0

- name: Fallback to docker.io registry
  when: rdo_pull_success.changed
  block:

    - name: List down missing containers
      set_fact:
        rdo_missing_containers: "{{ rdo_missing_containers | default([]) + [item] }}"
      when: item.rc != 0
      loop: "{{ rdo_pull_success.results }}"

    - name: Pull failed containers from dockerhub
      become: true
      command: "podman pull {{ item.split('/')[-1] }}"
      register: docker_pull_success
      loop: "{{ rdo_missing_containers }}"
      changed_when: false
      when: rdo_missing_containers is defined

    - name: Fail the job on failure of all fallback registry
      when: docker_pull_success.changed
      block:

        - name: List down missing containers
          set_fact:
            docker_missing_containers: "{{ docker_missing_containers | default([]) + [item] }}"
          when: item.rc != 0
          loop: "{{ docker_pull_success.results }}"

        - name: Fail the job if missing containers exists
          assert:
            that:
              - "docker_missing_containers | len > 0"
          when: docker_missing_containers is defined

- name: Push non-tripleo containers to the content provider registry
  become: true
  block:

    - name: Make sure buildah is installed
      package:
        name: "buildah"
        state: present

    # NOTE(mwhahaha): use buildah because --format can only be specified with buildah push.
    # Additionally we could switch to oci, but v2v2 is what we convert on the undercloud.
    - name: Pull non-tripleo containers (ceph, alertmanager, prometheus) to the content provider registry
      shell: >
        buildah images;
        buildah push --format=v2s2 --tls-verify=False --log-level debug {{ item }} \
          docker://{{ content_provider_registry_ip }}:{{ content_provider_registry_port }}/{{ docker_registry_namespace }}/{{ item.split('/')[-1] }};
      with_items: "{{ non_tripleo_containers }}"
      register: non_tripleo
      changed_when: false
      tags:
        - skip_ansible_lint

- name: Dump non-tripleo containers output to file
  copy:
    content: "{{ non_tripleo }}"
    dest: "{{ ansible_user_dir }}/non_tripleo_containers.log"
  when: non_tripleo is defined
