---

overcloud_ipv6: false
containerized_overcloud: false
deployed_server: false
containerized_overcloud_upgrade: false
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates
enable_tls_everywhere: false
undercloud_network_cidr: 192.168.24.0/24
timestamper_cmd: >-
    | awk '{ print strftime("%Y-%m-%d %H:%M:%S |"), $0; fflush(); }'
