---

overcloud_ipv6: false
containerized_overcloud: >-
  {% if release in ['newton', 'ocata', 'pike'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
containerized_undercloud: >-
  {% if release not in ['newton','ocata','pike','queens'] -%}
  true
  {%- else -%}
  false
  {%- endif -%}
containerized_overcloud_upgrade: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
undercloud_container_cli: >-
  {% if release in ['rocky'] -%}
  docker
  {%- else -%}
  podman
  {%- endif -%}
# the variable is only used in overcloud-deploy role
# for stein and beyond, so it's safe to set it to podman,
# as for stable branches before stein the variable won't be used.
overcloud_container_cli: podman
local_docker_registry_host: "{{ undercloud_network_gateway|default(undercloud_network_cidr|nthhost(1)) }}"
docker_registry_host: docker.io
docker_registry_namespace: "tripleo{{ release }}"
docker_image_tag: current-tripleo
# docker prefix
docker_prep_prefix: "{{ ansible_distribution | lower }}-binary-"
# docker suffix
docker_prep_suffix: ""
docker_ceph_namespace: docker.io/ceph
docker_ceph_image: daemon
docker_ceph_tag: >-
  {% if release in ['pike'] -%}
  v3.0.3-stable-3.0-jewel-centos-7-x86_64
  {%- elif release in ['queens','rocky'] -%}
  v3.2.1-stable-3.2-luminous-centos-7-x86_64
  {%- else -%}
  v4.0.0-stable-4.0-nautilus-centos-7-x86_64
  {%- endif -%}
rhel_containers: >-
   {% if ansible_distribution == 'RedHat' -%}
   true
   {%- else -%}
   false
   {%- endif -%}
additional_insecure_registry: false
deployed_server: false
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates
enable_tls_everywhere: false
undercloud_generate_service_certificate: true
undercloud_network_cidr: 192.168.24.0/24
undercloud_undercloud_nameservers:
  - 8.8.8.8
timestamper_cmd: >-
    | awk '{ print strftime("%Y-%m-%d %H:%M:%S |"), $0; fflush(); }'
# if virtbmc is enabled we can assume a libvirt setup and the libvirt
# tripleo ui steps will also execute.
# enable_libvirt_tripleo_ui is a switch to force the steps to run with or
# without virtbmc
enable_libvirt_tripleo_ui: false
composable_scenario: ""
upgrade_composable_scenario: ""
artcl_collect_dir: "{{ local_working_dir }}/collected_files"
undercloud_rpm_dependencies: >-
  python-tripleoclient

# moved from overcloud-deploy
# If `test_ping` is `true`, run a simple ping test to validate the
# overcloud.
test_ping: true

# install and execute dstat across nodes
validate_performance: true

# If `validate_services` is `true`, run the validate-services role
validate_services: false

# If `baremetal_provision` is `true`, deploy baremetal with "openstack overcloud node provision" and deployed-server, instead of with heat/nova
baremetal_provision: false

# If `undercloud_enable_nova` is `true`, the undercloud will have running glance and nova services
undercloud_enable_nova: true
