---
- name: gather facts used by role
  setup:
    gather_subset: "!min,distribution"
  when: ansible_distribution is not defined

- name: Run podman --version
  command: podman --version
  ignore_errors: true
  register: podman_ver
  tags:
    - undercloud-install
  changed_when: false


- name: Set fact for podman version
  set_fact:
    podman_version: >-
      {%- if podman_ver is success -%}
      {{ podman_ver.stdout | replace("podman version ", "") }}
      {%- else -%}0.0
      {%- endif -%}
  tags:
    - undercloud-install


- include: novajoin_prep.yml
  when: enable_tls_everywhere|bool and prepare_novajoin|bool
  tags:
    - undercloud-install

# NOTE(aschultz): this creates all the magical config related items, will
# want to extract the script part from configs
- include: create-scripts.yml
  tags:
    - undercloud-scripts

- name: Run install via tripleo-operator-ansible
  when:
    - release in ['master']
    - step_install_undercloud|bool
  tags:
    - undercloud-install
  block:
    - name: Run dstat on the undercloud prior to undercloud install
      include_role:
        name: validate-perf

    - name: Install undercloud
      collections:
        - tripleo.operator
      include_role:
        name: tripleo_undercloud_install
      vars:
        tripleo_undercloud_install_debug: "{{ undercloud_undercloud_debug }}"

# TODO(mwhahaha): remove this after backwards compatibility support
- name: Run legacy install
  when: release not in ['master']
  tags:
    - undercloud-install
  block:
    - include: install-undercloud.yml


# Ironic defaults to using `qemu:///system`.  When running libvirtd
# unprivileged we need to use `qemu:///session`.  This allows us to pass
# the value of libvirt_uri into /etc/ironic/ironic.conf.
- name: Configure Ironic pxe_ssh driver
  when: release in ['mitaka', 'liberty']
  delegate_to: undercloud
  ini_file:
    dest: /etc/ironic/ironic.conf
    section: ssh
    option: libvirt_uri
    value: '{{ libvirt_uri }}'
  become: true
  tags:
    - undercloud-install

- name: restart ironic conductor after changing configuration
  when: release in ['mitaka', 'liberty']
  become: true
  service:
    name: openstack-ironic-conductor
    enabled: true
    state: restarted
  tags:
    - undercloud-install

- include: post-install.yml
  tags:
    - undercloud-post-install

- include: tripleo-ui.yml
  tags:
    - undercloud-post-install
  when: (enable_vbmc|bool and undercloud_enable_ui|bool) or enable_libvirt_tripleo_ui|bool
