# Generate a number of scripts from templates.  These are scripts
# rather than additional ansible tasks so that they can be run
# manually from the undercloud host.
- name: Create overcloud deploy script
  template:
    src: "{{ deploy_script }}"
    dest: "{{ working_dir }}/overcloud-deploy.sh"
    mode: 0755

- name: Create post-deploy script
  template:
    src: "{{ post_deploy_script }}"
    dest: "{{ working_dir }}/overcloud-deploy-post.sh"
    mode: 0755

- name: Copy neutron l3 ha heat template
  when: enable_pacemaker|bool and number_of_controllers|int < 3
  template:
    src: "neutronl3ha.yaml.j2"
    dest: "{{ working_dir }}/neutronl3ha.yaml"

- name: Copy composable services file
  when: composable_services|bool
  template:
    src: "overcloud_services.yaml.j2"
    dest: "{{ working_dir }}/overcloud_services.yaml"

- name: Cloud names heat environment
  when: release not in ['mitaka', 'liberty']
  template:
    src: "cloud-names.yaml.j2"
    dest: "{{ working_dir }}/cloud-names.yaml"

