# Note.. the order of heat templates and args is very important.  The last environment that sets a variable takes precedent.

- name: set network_args fact
  set_fact:
    network_args: >-
      -e {{ overcloud_templates_path }}/environments/network-isolation.yaml
      -e {{ overcloud_templates_path }}/environments/net-single-nic-with-vlans.yaml
      -e {{ working_dir }}/network-environment.yaml
  when:
    - network_isolation|bool
    - not overcloud_ipv6|bool
    - not containerized_overcloud|bool

- name: set network_args fact for IPv6
  set_fact:
    network_args: >-
      -e {{ overcloud_templates_path }}/environments/network-isolation-v6.yaml
      -e {{ overcloud_templates_path }}/environments/net-multiple-nics-v6.yaml
      -e {{ working_dir }}/network-environment.yaml
  when:
    - network_isolation|bool
    - overcloud_ipv6|bool

- name: enable pacemaker
  set_fact:
    pacemaker_args: >-
      -e {{ overcloud_templates_path }}/environments/puppet-pacemaker.yaml
  when: enable_pacemaker|bool

- name: extract the number of controllers to be deployed
  set_fact: number_of_controllers="{{ deploy_args| regex_replace('^.*--control-scale +([0-9]+).*$', '\\1') | regex_replace('^[^ 0-9]*.*$', '1') }}"

- name: Set cinder-backup
  set_fact:
    backup_args: >-
      -e {{ overcloud_templates_path }}/environments/cinder-backup.yaml
  when: enable_cinder_backup|bool

- name: Set cloud-name variables
  set_fact:
      cloud_name_args: >-
          -e {{ working_dir }}/cloud-names.yaml
  when: release not in ['mitaka', 'liberty']

- name: set ssl_args fact for master/newton
  set_fact:
    ssl_args: >-
      -e {{ working_dir }}/enable-tls.yaml
      -e {{ overcloud_templates_path }}/environments/tls-endpoints-public-ip.yaml
      -e {{ working_dir }}/inject-trust-anchor.yaml
  when:
    - ssl_overcloud|bool
    - release in ['newton', 'master']

- name: set ssl_args fact for mitaka/liberty
  set_fact:
    ssl_args: >-
      -e {{ working_dir }}/enable-tls.yaml
      -e {{ working_dir }}/inject-trust-anchor.yaml
  when:
    - ssl_overcloud|bool
    - release in ['mitaka', 'liberty']

- name: set novajoin/TLS everywhere fact
  set_fact:
      tls_everywhere_args: >-
          -e {{ overcloud_templates_path }}/environments/services/haproxy-public-tls-certmonger.yaml
          -e {{ overcloud_templates_path }}/environments/enable-internal-tls.yaml
          -e {{ overcloud_templates_path }}/environments/tls-everywhere-endpoints-dns.yaml
  when:
    - enable_tls_everywhere|bool
    - release not in ['mitaka', 'liberty', 'newton']

- name: set validation_args fact for mitaka/liberty
  set_fact:
    validation_args: "--validation-errors-fatal --validation-warnings-fatal"
  when: release in ['mitaka', 'liberty']

- name: disable L3 HA
  set_fact:
    pacemaker_args: >-
      {{ pacemaker_args }}
      -e {{ working_dir }}/neutronl3ha.yaml
  when:
    - enable_pacemaker|bool
    - number_of_controllers|int < 3

- name: set workers_args fact
  set_fact:
    workers_args: >-
      -e {{ overcloud_templates_path }}/environments/low-memory-usage.yaml
  when: release not in ['mitaka', 'liberty']

- name: Use KVM for Red Hat distro
  set_fact: libvirt_args="--libvirt-type kvm"
  when: ansible_distribution == 'RedHat'

- name: set container_args fact
  set_fact:
    container_args: >-
      -e {{ overcloud_templates_path }}/environments/docker.yaml
      -e {{ overcloud_templates_path }}/environments/docker-network.yaml
      -e {{ working_dir }}/containers-default-parameters.yaml
  when:
    - containerized_overcloud|bool
    - not network_isolation|bool

- name: set network_args fact for containers
  set_fact:
    network_args: >-
      -e {{ overcloud_templates_path }}/environments/docker.yaml
      -e {{ overcloud_templates_path }}/environments/network-isolation.yaml
      -e {{ overcloud_templates_path }}/environments/net-single-nic-with-vlans.yaml
      -e {{ working_dir }}/network-environment.yaml
      -e {{ working_dir }}/containers-default-parameters.yaml
  when:
    - network_isolation|bool
    - containerized_overcloud|bool

- name: set composable service args fact
  set_fact:
    extra_args: >-
      {{ extra_args }}
      -e {{ working_dir }}/overcloud_services.yaml
  when: composable_services

- name: set the scenario args for composable roles
  set_fact:
    scenario_args: >-
      -e {{ overcloud_templates_path }}/ci/environments/{{ composable_scenario }}
  when: deploy_composable_scenario|bool

- name: set swap_args to enable swap file
  set_fact:
    swap_args: >-
      -e {{ overcloud_templates_path }}/environments/enable-swap.yaml
  when: enable_swap|bool and swap_type == 'file'

- name: set swap_args to enable swap partition
  set_fact:
    swap_args: >-
      -e {{ overcloud_templates_path }}/environments/enable-swap-partition.yaml
  when: enable_swap|bool and swap_type == 'partition'
