---

control_memory: 6144
compute_memory: 6144

undercloud_memory: 8192
undercloud_vcpu: 2

overcloud_nodes:
  - name: control_0
    flavor: control

  - name: compute_0
    flavor: compute

  - name: compute_1
    flavor: compute

  - name: compute_2
    flavor: compute

tempest: false
pingtest: true
deploy_timeout: 60

# General deployment info
libvirt_args: "--libvirt-type qemu"
flavor_args: >-
  --control-flavor {{flavor_map.control
  if flavor_map is defined and 'control' in flavor_map else 'oooq_control'}}
  --compute-flavor {{flavor_map.compute
  if flavor_map is defined and 'compute' in flavor_map else 'oooq_compute'}}
  --ceph-storage-flavor {{flavor_map.ceph
  if flavor_map is defined and 'ceph' in flavor_map else 'oooq_ceph'}}
timeout_args: "--timeout {{ deploy_timeout }}"
extra_args: "--compute-scale 1 --neutron-network-type vxlan --neutron-tunnel-types vxlan -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml -e /usr/share/openstack-tripleo-heat-templates/environments/net-single-nic-with-vlans.yaml -e ~/network-environment.yaml --ntp-server pool.ntp.org"
# Pulled this out so we can hand these configs to the openstack overcloud node delete command
scale_extra_configs: "-e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml -e /usr/share/openstack-tripleo-heat-templates/environments/net-single-nic-with-vlans.yaml -e ~/network-environment.yaml"
scale_extra_args: "--{{ node_to_scale }}-scale {{ final_scale_value }} --neutron-network-type vxlan --neutron-tunnel-types vxlan {{ scale_extra_configs }} --ntp-server pool.ntp.org"


# Scale deployment info
node_to_scale: compute # Type of node to scale
initial_scale_value: 1 # Initial number of nodes to deploy
final_scale_value: 2   # Number of additional nodes to add during the scale

# Initial deployment arguments
deploy_args: >-
  {{ libvirt_args }}
  {{ flavor_args }}
  {{ timeout_args }}
  {{ extra_args  }}

# Scale deployment arguments
scale_args: >-
  {{ libvirt_args }}
  {{ flavor_args }}
  {{ timeout_args }}
  {{ scale_extra_args }}

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - scale-deployment
    - delete-node
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
    - scale-deployment
    - delete-node
    - overcloud-validate

# Sample call
# ./deploy.sh -v --playbook scale_nodes --config-file config/scale/scale_compute.yml
