---

overcloud_prep_images_script: overcloud-prep-images.sh.j2
overcloud_prep_images_log: "{{ working_dir }}/overcloud_prep_images.log"

step_overcloud_image: true
step_glance_upload: false
step_register: true
step_introspect: false
step_introspect_debug: false
step_introspect_debug_tcpdump_log: "{{ working_dir }}/overcloud_prep_images_introspection_debug.pcap.log"
step_introspect_with_retry: false
bash_deploy_ramdisk: false
step_install_undercloud: true
step_root_device_size: false
disk_root_device_size: 1843
step_root_device_hints: false
root_device_hints: []
whole_disk_images: false

download_overcloud_image: false
overcloud_full_tar_name: overcloud-full.tar
