---

undercloud_config_file: undercloud.conf.j2
undercloud_install_script: undercloud-install.sh.j2
undercloud_install_log: "{{ working_dir }}/undercloud_install.log"
network_environment_file: network-environment.yaml.j2
undercloud_hieradata_override_file: quickstart-hieradata-overrides.yaml.j2

undercloud_network_cidr: 192.168.24.0/24

step_introspect: false
bash_deploy_ramdisk: false
step_install_undercloud: true

# Which libvirt session should we use?  Using `qemu://session` does
# not require privileged access (but does require the setup performed by the
# `environment/setup` role).
libvirt_uri: qemu:///session

# port to use for httpd ipxe server for ironic deploy
undercloud_ironic_ipxe_port: 3816

enable_vbmc: true
undercloud_conf_extra: ""

prepare_novajoin: true
