---

undercloud_config_file: undercloud.conf.j2
undercloud_post_install_script: undercloud-install-post.sh.j2
undercloud_install_log: "{{ working_dir }}/undercloud_install.log"

# default undercloud install method
# containerized_undercloud is an EXPERIMENTAL FEATURE
containerized_undercloud: false
undercloud_docker_registry_host: "{{ docker_registry_host }}"
undercloud_docker_registry_namespace: "{{ docker_registry_namespace }}"
undercloud_docker_image_tag: "{{ docker_image_tag }}"
undercloud_install_script: undercloud-install.sh.j2

# defines a custom undercloud roles file should be used with
# openstack overcloud container image prepare (and undercloud deploy, in future)
# FIXME(bogdando): do not attempt to change it yet the client's hardcode is fixed
undercloud_roles_data: "{{overcloud_templates_path}}/roles_data_undercloud.yaml"

# defines extra args and service templates for the undercloud deploy command
undercloud_extra_args: ""
undercloud_extra_services_args: >-
  -e {{overcloud_templates_path}}/environments/services-docker/ironic.yaml
  -e {{overcloud_templates_path}}/environments/services-docker/ironic-inspector.yaml
  -e {{overcloud_templates_path}}/environments/services-docker/mistral.yaml
  -e {{overcloud_templates_path}}/environments/services-docker/zaqar.yaml
  -e {{overcloud_templates_path}}/environments/docker.yaml

# The undercloud can also be deployed with heat
# thus requiring a t-h-t driven undercloud *and* the classic undercloud
# override file
hieradata_override_file_classic_undercloud: hieradata-overrides-classic-undercloud.yaml.j2
hieradata_override_file_t_h_t_undercloud: hieradata-overrides-t-h-t-undercloud.yaml.j2

step_introspect: false
bash_deploy_ramdisk: false
step_install_undercloud: true

# The TripleO-UI is available on the undercloud
# ssl or non-ssl access can be configured
# Due to self signed certificates a user must grant permission to
# https://<virthost>/keystone/v3/auth/tokens for ssl access to work.
tripleo_ui_secure_access: false

# Which libvirt session should we use?  Using `qemu://session` does
# not require privileged access (but does require the setup performed by the
# `environment/setup` role).
libvirt_uri: qemu:///session

# port to use for httpd ipxe server for ironic deploy
undercloud_ironic_ipxe_port: 3816

enable_vbmc: true
undercloud_conf_extra: ""

undercloud_enable_novajoin: false
prepare_novajoin: true

# location which the novajoin-ipa-setup will store the FreeIPA token
freeipa_otp_key: /tmp/ipa-otp.txt

# determines vendordata_dynamic_connect|read_timeout when novajoin is enabled
novajoin_connect_timeout: 5
novajoin_read_timeout: 20

libvirt_default_network_address: 192.168.122.1

# only to be used in libvirt deployments, see environment config for details
nameserver_from_virthost: false
virthost_nameservers: []

undercloud_enable_mistral: true
undercloud_enable_monitoring: false
undercloud_enable_telemetry: true
undercloud_enable_tempest: true
undercloud_enable_ui: true
undercloud_enable_validations: true
undercloud_ipxe_deploy: true

undercloud_undercloud_debug: true

# Use to populate the resource registry for nic configs and networking setup
undercloud_resource_registry_args:
  OS::TripleO::Undercloud::Net::SoftwareConfig: "{{overcloud_templates_path}}/net-config-noop.yaml"
undercloud_network_environment_args:
  UndercloudNetworkCidr: "{{undercloud_network_cidr}}"
  UndercloudDhcpRangeStart: "{{undercloud_dhcp_start|default(
    undercloud_network_cidr|nthhost(5))}}"
  UndercloudDhcpRangeEnd: "{{undercloud_dhcp_end|default(
    undercloud_network_cidr|nthhost(30))}}"
  UndercloudNetworkGateway: "{{undercloud_network_gateway|default(
    undercloud_network_cidr|nthhost(1))}}"
  UndercloudNameserver: "{% if undercloud_undercloud_nameservers is string %}{{undercloud_undercloud_nameservers.split(',')[0]}}{% else %}{{undercloud_undercloud_nameservers[-1]}}{% endif %}"
  NeutronServicePlugins: ""
  ControlPlaneSubnetCidr: 24
