---

undercloud_config_file: undercloud.conf.j2
undercloud_post_install_script: undercloud-install-post.sh.j2
undercloud_install_log: "{{ working_dir }}/undercloud_install.log"
network_environment_file: network-environment.yaml.j2

# default undercloud install method
# containerized_undercloud is an EXPERIMENTAL FEATURE
containerized_undercloud: false
undercloud_install_script: undercloud-install.sh.j2

# The undercloud can also be deployed with heat
# thus requiring a t-h-t driven undercloud *and* the classic undercloud
# override file
hieradata_override_file_classic_undercloud: hieradata-overrides-classic-undercloud.yaml.j2
hieradata_override_file_t_h_t_undercloud: hieradata-overrides-t-h-t-undercloud.yaml.j2

step_introspect: false
bash_deploy_ramdisk: false
step_install_undercloud: true

# Which libvirt session should we use?  Using `qemu://session` does
# not require privileged access (but does require the setup performed by the
# `environment/setup` role).
libvirt_uri: qemu:///session

# port to use for httpd ipxe server for ironic deploy
undercloud_ironic_ipxe_port: 3816

enable_vbmc: true
undercloud_conf_extra: ""

undercloud_enable_novajoin: false
prepare_novajoin: true

# location which the novajoin-ipa-setup will store the FreeIPA token
freeipa_otp_key: /tmp/ipa-otp.txt

# determines vendordata_dynamic_connect|read_timeout when novajoin is enabled
novajoin_connect_timeout: 5
novajoin_read_timeout: 20

libvirt_default_network_address: 192.168.122.1
