---

undercloud_config_file: undercloud.conf.j2
undercloud_install_cli_options: ""
undercloud_post_install_script: undercloud-install-post.sh.j2
undercloud_install_log: "{{ working_dir }}/undercloud_install.log"

undercloud_install_script: undercloud-install.sh.j2

# defines extra args for the undercloud deploy command
undercloud_extra_args: ""

# The undercloud can also be deployed with heat
# thus requiring a t-h-t driven undercloud *and* the classic undercloud
# override file
hieradata_override_file_classic_undercloud: hieradata-overrides-classic-undercloud.yaml.j2
hieradata_override_file_t_h_t_undercloud: hieradata-overrides-t-h-t-undercloud.yaml.j2

step_introspect: false
bash_deploy_ramdisk: false
step_install_undercloud: true

# The TripleO-UI is available on the undercloud
# ssl or non-ssl access can be configured
# Due to self signed certificates a user must grant permission to
# https://<virthost>/keystone/v3/auth/tokens for ssl access to work.
tripleo_ui_secure_access: false

# Which libvirt session should we use?  Using `qemu://session` does
# not require privileged access (but does require the setup performed by the
# `environment/setup` role).
libvirt_uri: qemu:///session

# port to use for httpd ipxe server for ironic deploy
undercloud_ironic_ipxe_port: 3816

undercloud_conf_extra: ""

undercloud_enable_novajoin: false
prepare_novajoin: true

# location which the novajoin-ipa-setup will store the FreeIPA token
freeipa_otp_key: /tmp/ipa-otp.txt

# determines vendordata_dynamic_connect|read_timeout when novajoin is enabled
novajoin_connect_timeout: 5
novajoin_read_timeout: 20

libvirt_default_network_address: 192.168.122.1

# only to be used in libvirt deployments, see environment config for details
nameserver_from_virthost: false
virthost_nameservers: []

undercloud_enable_ironic: true
undercloud_enable_ironic_inspector: true
undercloud_enable_mistral: true
undercloud_enable_monitoring: false
undercloud_enable_telemetry: false
undercloud_enable_tempest: false
undercloud_enable_ui: true
undercloud_enable_validations: true
undercloud_enable_zaqar: true
undercloud_ipxe_deploy: true
undercloud_enable_swift_encryption: false

undercloud_undercloud_debug: true

# Path to tripleo-heat-templates to be cloned from given repo/branch/refscpec
undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# Use to populate the resource registry for nic configs and networking setup
undercloud_resource_registry_args: {}
undercloud_network_environment_args: {}

ctlplane_masquerade: false

update_containers: false
gating_repo_name: gating-repo
update_containers_repo: "{{ gating_repo_name }},delorean-current"
undercloud_enable_routed_networks: false

default_undercloud_roles_data_path: "{{ undercloud_templates_path }}/roles_data_undercloud.yaml"

# We disable selinux when running under CentOS. It's enabled for RHEL
undercloud_selinux_enabled: >-
   {% if ansible_distribution == 'CentOS' -%}
   false
   {%- else -%}
   true
   {%- endif -%}

undercloud_container_cli: docker

# Define a custom t-h-t installation for UC
undercloud_custom_tht_script: custom-tht-script.sh.j2
undercloud_custom_tht_log: undercloud_custom_tht_script.log

# FIXME(bogdando) adapt these for real UC upgrade/deploy cases.
# As the tht prep config templates converged with the overcloud upgrade/deploy cases,
# these are yet meaningless for undercloud installations so the defaults
# are set only to disable the controlled code blocks.
undercloud_composable_scenario: ""
undercloud_upgrade_composable_scenario: ""
undercloud_prep_post_hook_script: ""
undercloud_tht_rpm_url: ""
download_undercloud_templates_rpm: false
