---
# Configure the undercloud to use ARA
# for ansible undercloud or standalone only.  Ansible deployment of node
- name: Install ara deps
  become: true
  pip:
    name:
      - pip
      - setuptools
    state: latest
  # TODO(sshnaidm): https://bugs.launchpad.net/tripleo/+bug/1792622
  ignore_errors: true

- name: Install ara
  become: true
  pip:
    name: ara
    state: present
    version: "{{ undercloud_ara_version }}"
  ignore_errors: true

- name: Update the default ansible callback setting in /etc/ansible/ansible.cfg
  become: true
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: '^#callback_plugins'
    line: |
      callback_plugins={% if ansible_python.version.major == 3 %}/usr/local/lib/python3.6/site-packages{% else %}/usr/lib/python2.7/site-packages{% endif %}/ara/plugins/callbacks

- name: Update the default ansible action setting in /etc/ansible/ansible.cfg
  become: true
  lineinfile:
    path: /etc/ansible/ansible.cfg
    regexp: '^#action_plugins'
    line: |
      action_plugins={% if ansible_python.version.major == 3 %}/usr/local/lib/python3.6/site-packages{% else %}/usr/lib/python2.7/site-packages{% endif %}/ara/plugins/actions
