---

- name: Install the TripleO-CI VXLAN networking script on subnodes
  template:
    src: toci_vxlan_networking_multinode.sh.j2
    dest: "{{ working_dir }}/toci_vxlan_networking_multinode.sh"
    mode: 0755
  when: toci_vxlan_networking_multinode|bool

- name: Run the TripleO-CI VXLAN networking script on subnodes
  shell: >
    set -o pipefail &&
    timeout --preserve-status 60s {{ working_dir }}/toci_vxlan_networking_multinode.sh
    2>&1 {{ timestamper_cmd }} > {{ working_dir }}/toci_vxlan_networking_multinode.sh.log
  when: toci_vxlan_networking_multinode|bool

- name: Install the TripleO-CI VXLAN networking script
  copy:
    src: toci_vxlan_networking.sh
    dest: "{{ working_dir }}/toci_vxlan_networking.sh"
    mode: 0755

- name: Run the TripleO-CI VXLAN networking script
  shell: >
    set -o pipefail &&
    {{ working_dir }}/toci_vxlan_networking.sh
    2>&1 {{ timestamper_cmd }} > {{ working_dir }}/toci_vxlan_networking.sh.log

