---
- name: Execute Tobiko
  shell: >
    set -o pipefail &&
    tools/ci/tox -e {{ tobiko_envlist }} {{ tobiko_extra_args }} 2>&1 {{ timestamper_cmd }} > {{ tobiko_log_dir }}/{{ tobiko_log_file }};
  args:
    chdir: "{{ working_dir }}/tobiko"
    executable: /bin/bash
  register: tobiko_tests_run
  ignore_errors: true
  environment:
    OS_CLOUD: "{{ tempest_cloud_name }}"
