---

network_isolation: true
network_isolation_type: single-nic-vlans # multiple-nics, bond-with-vlans, public-bond
network_environment_file: network-environment.yaml.j2

external_network_cidr: 192.168.23.0/24
undercloud_external_network_cidr: 10.0.0.1/24
undercloud_network_cidr: 192.168.24.0/24
overcloud_dns_servers: [ '{{ external_network_cidr|nthhost(1) }}' ]

overcloud_public_vip: 10.0.0.5
ssl_overcloud: false

network_environment_args:
  ExternalNetCidr: "{{ undercloud_external_network_cidr }}"
  ExternalAllocationPools: >
    [{'start': '{{ undercloud_external_network_cidr|nthhost(4) }}',
    'end': '{{ undercloud_external_network_cidr|nthhost(250) }}'}]
  NeutronExternalNetworkBridge: ""
  ControlPlaneSubnetCidr: "{{ undercloud_network_cidr|ipaddr('prefix') }}"
  ControlPlaneDefaultRoute: "{{ undercloud_network_cidr|nthhost(1) }}"
  EC2MetadataIp: "{{ undercloud_network_cidr|nthhost(1) }}"
  DnsServers: "{{ overcloud_dns_servers }}"

public_virtual_fixed_ips:
  PublicVirtualFixedIPs: >
    [{'ip_address':'{{ overcloud_public_vip }}'}]

undercloud_type: virtual
baremetal_instackenv: "{{ working_dir }}/instackenv.json"
baremetal_network_environment: "{{ working_dir }}/network-isolation.yml"

overcloud_custom_tht_script: overcloud-custom-tht-script.sh.j2
overcloud_custom_tht_log: overcloud_custom_tht_script.log

bond_with_vlans_copy_nic_configs_script: bond-with-vlans-copy-nic-configs.sh.j2
bond_with_vlans_nic_configs_log: bond_with_vlans_nic_configs_script_log
