- name: Prepare the network-isolation required networks on the undercloud
  shell: >
    set -o pipefail &&
    {{ working_dir }}/overcloud-prep-network.sh 2>&1 {{ timestamper_cmd }} >
    {{ overcloud_prep_network_log }}
