---
freeipa_internal_ip: "{{ hostvars['subnode-1'].inventory_ip }}"
standalone_hostname: "standalone-0.{{ tripleo_domain }}"
tripleo_domain: ooo.test
undercloud_cloud_domain: "{{ tripleo_domain }}"
freeipa_server_hostname: "ipa.{{ tripleo_domain }}"
overcloud_cloud_name: "overcloud.{{ tripleo_domain }}"
overcloud_cloud_domain: "{{ tripleo_domain }}"
overcloud_cloud_name_internal: "overcloud.internalapi.{{ tripleo_domain }}"
overcloud_cloud_name_storage: "overcloud.storage.{{ tripleo_domain }}"
overcloud_cloud_name_storage_management: "overcloud.storagemgmt.{{ tripleo_domain }}"
overcloud_cloud_name_ctlplane: "overcloud.ctlplane.{{ tripleo_domain }}"
freeipa_admin_password: fce95318204114530f31f885c9df588f
# vars for new tls work
enable_tls: true
ipa_domain: "{{ tripleo_domain }}"
cloud_domain: "{{ tripleo_domain }}"
ipa_nameserver: "ipa.{{ tripleo_domain }}"
ipa_realm: "{{ ipa_domain | upper }}"
freeipa_directory_password: "{{ freeipa_admin_password }}"
freeipa_principal: admin
tls_packages:
  - python3-pip
  - openssl-perl
ipa_packages:
  - ipa-server
  - ipa-server-dns
  - curl
  - iptables
