---
- name: gather facts used by role
  setup:
    gather_subset: "!min,python,processor"
  when: >
    python_version is not defined or
    ansible_processor_vcpus is not defined

- name: gather ansible_python_version
  setup:
    gather_subset: "!min,python_version,python"
  when: >
    ansible_python_version is not defined or
    ansible_python is not defined

- name: set python_cmd
  set_fact:
    python_cmd: "python{{ ansible_python.version.major }}"
    cacheable: true
  when: python_cmd is not defined

- include: tempest-venv.yml
  when: tempest_config|bool and tempest_format == 'venv'
  tags:
    - pre-tempest-config

- include: tempest-rpm.yml
  when: tempest_config|bool and tempest_format == 'packages'
  tags:
    - pre-tempest-config

- include: tempest-containers.yml
  when: tempest_config|bool and tempest_format == 'container'
  tags:
    - pre-tempest-config

- include: pre-tempest.yml
  when: tempest_config|bool or run_tempest|bool
  tags:
    - pre-tempest-config

- include: run-tempest.yml
  when: run_tempest|bool
  tags:
    - run-tempest

- include: tempest-results.yml
  when: run_tempest|bool
  tags:
    - tempest-results

- include: stackviz.yml
  when: run_tempest|bool
  tags:
    - run-stackviz
  ignore_errors: yes

- include: post-tempest.yml
  when: post_tempest|bool and run_tempest|bool
  tags:
    - post-tempest
