---
- name: Install openstack services tempest plugin
  package: name={{ item }} state=present
  become: true
  with_items:
    - python-ceilometer-tests
    - python-zaqar-tests
    - python-ironic-inspector-tests
    - python-gnocchi-tests
    - python-aodh-tests
    - python-mistral-tests
    - python-heat-tests
    - python-keystone-tests
    - python-ironic-tests
    - python-neutron-tests
    - python-cinder-tests
  when: release == 'newton'

- name: Install openstack services tempest plugins
  yum: state=latest name={{ item }}
  with_items: "{{ tempest_plugins }}"
  become: true
  when: tempest_plugins|length > 0

- name: Install openstack tempest
  package: name={{ item }} state=present
  become: true
  with_items:
    - openstack-tempest
    - python-junitxml

- name: Install python-tempestconf
  package:
    name: python-tempestconf
    state: present
  become: true
  when: release != 'newton'

- name: Set tempest init command
  set_fact:
    tempest_init: "{% if release == 'newton' %}/usr/share/openstack-tempest-*/tools/configure-tempest-directory{% else %}tempest init {{ tempest_dir }}{% endif %}"

- name: Set tempestconf call
  set_fact:
    tempestconf: "{% if release == 'newton' %}{{ tempest_dir }}/tools/config_tempest.py{% else %}/usr/bin/discover-tempest-config{% endif %}"
