---
# Add the virthost to the in-memory inventory.  The inventory is not
# wirtten out to disk unless you call the `rebuild-inventory` role.
- name: Add the virthost to the inventory
  hosts: localhost
  tasks:
    - add_host:
        name: "{{virthost}}"
        groups: "virthost"
        ansible_fqdn: "{{ virthost }}"
        ansible_user: "root"
        ansible_host: "{{ virthost }}"

# Add the virthost node to the generated
# inventory.
- name:  Inventory the virthost
  hosts: localhost
  gather_facts: yes
  roles:
    - { role: tripleo-inventory }

- include: teardown.yml

- include: provision.yml

# The `environment/setup` role performs any tasks that require `root`
# access on the target host.
- name: Install libvirt packages and configure networks
  hosts: virthost
  tags:
    - environment
  roles:
    - environment/setup

- name:  Setup undercloud and baremetal vms and networks in libvirt
  hosts: virthost
  gather_facts: yes
  roles:
    - libvirt/setup

# Add the undercloud node to the generated
# inventory.
- name:  Inventory the undercloud
  hosts: localhost
  gather_facts: yes
  vars:
      inventory: undercloud
  roles:
    - tripleo-inventory

- name: Prepare the host for PXE forwarding
  hosts: virthost
  gather_facts: no
  roles:
    - baremetal-prep-virthost

- name: Validate IPMI and instackenv.json
  hosts: undercloud
  gather_facts: no
  roles:
    - validate-ipmi

- name:  Install the undercloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud

- name:  Post undercloud install steps
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-undercloud-post

- name:  Perpare the baremetal overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - baremetal-overcloud

- name:  Deploy the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-overcloud

# Add the overcloud nodes to the generated inventory.
- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: yes
  vars:
      inventory: all
  roles:
    - tripleo-inventory

- name:  validate the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-overcloud-validate
