---
- name: Validate IPMI and instackenv.json
  hosts: undercloud
  gather_facts: yes
  roles:
    - { role: validate-ipmi,
        when: not use_testenv_broker|default(false)|bool }

- name:  Deploy the undercloud
  hosts: undercloud
  gather_facts: no
  roles:
    - undercloud-deploy

- name: Configure tripleo-validations
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    run_tripleo_validations_setup: True
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}

- name: Build images for quickstart
  hosts: undercloud
  gather_facts: no
  roles:
    - { role: build-images, when: to_build|default(false)|bool }
  tags:
    - get-images
    - images

- name:  copy over config files
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-config

- name:  Perpare the baremetal overcloud
  hosts: undercloud
  gather_facts: yes
  roles:
    - baremetal-prep-overcloud

- name:  Prepare overcloud containers
  hosts: undercloud
  gather_facts: no
  roles:
    - { role: overcloud-prep-containers, when: containerized_overcloud|bool }

- name:  Prepare the overcloud images for deployment
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-images

- name: Run tripleo-validations pre-introspection tests
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    validations_group: ['pre-introspection']
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}


- name:  Prepare overcloud flavors
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-flavors

- name:  Prepare the undercloud networks for the overcloud deployment
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-network

- name: Prepare the SSL Configuration for the overcloud deployment
  hosts: undercloud
  gather_facts: no
  roles:
    - { role: overcloud-ssl, when: ssl_overcloud|bool }

- name: Run tripleo-validations pre-deployment tests
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    validations_group: ['pre-deployment']
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}


- name:  Deploy the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-deploy

- name: Run tripleo-validations post-deployment tests
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    validations_group: ['post-deployment']
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}


# Add the overcloud nodes to the generated inventory.
- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: yes
  tags:
    - overcloud-deploy
  vars:
      inventory: all
  roles:
    - tripleo-inventory

- name:  Check the result of the deployment
  hosts: localhost
  tags:
    - overcloud-deploy
  tasks:
    - name: ensure the deployment result has been read into memory
      include_vars: "{{ local_working_dir }}/overcloud_deployment_result.json"

    # overcloud_deploy_result = ["failed", "passed"]
    - name: did the deployment pass or fail?
      debug: var=overcloud_deploy_result
      failed_when: overcloud_deploy_result == "failed"

# Execute sanity checks agsinst the overcloud deployment
- name: Sanity check the overcloud services
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-sanity-checks,
        when: run_sanity_checks|default(false)|bool }

# Validate the deployment
- name:  validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-simple, when: test_ping|bool }

# Execute tempest against the overcloud deployment
- name:  Execute tempest against the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-tempest, when: run_tempest|bool }

