---
# Execute sanity checks agsinst the overcloud deployment
- name: setup dstat performance monitoring
  hosts: overcloud
  tags:
    - overcloud-validate
  roles:
    - {role: validate-perf,
       when: validate_performance|bool and run_tempest|bool}
  ignore_errors: true

- name: Sanity check the overcloud services
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: false
  roles:
    - {role: validate-sanity-checks,
       when: run_sanity_checks|default(false)|bool}

# Validate the deployment
- name: validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: false
  roles:
    - {role: validate-simple, when: test_ping|bool}

# Execute tempest against the overcloud deployment
- name: Validate the deployment
  hosts: undercloud
  tasks:
    - include_tasks: tasks/tempest.yml
      vars:
        tempest_install_method: distro
        tempest_cloud_name: 'overcloud'
  tags:
    - overcloud-validate

- name: Delete the overcloud
  hosts: undercloud
  tags:
    - overcloud-delete
  gather_facts: false
  roles:
    - {role: overcloud-delete,
       when: step_delete_overcloud|default(false)|bool}
