---
# Execute sanity checks agsinst the overcloud deployment
- name: setup dstat performance monitoring
  hosts: overcloud
  tags:
    - overcloud-validate
  roles:
    - {role: validate-perf,
       when: validate_performance|bool and use_os_tempest | default(true) | bool}
  ignore_errors: true

- name: Sanity check the overcloud services
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: false
  roles:
    - {role: validate-sanity-checks,
       when: run_sanity_checks|default(false)|bool}

# Validate the deployment
- name: validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: false
  roles:
    - {role: validate-simple, when: test_ping|bool}

- name: Execute netstat for port audit
  hosts: overcloud
  vars:
    execute_netstat: true
  roles:
    - overcloud-network-discovery
  tags:
    - overcloud-validate

# Execute tempest against the overcloud deployment
- name: Validate the deployment
  hosts: undercloud
  tasks:
    - include_tasks: tasks/tempest.yml
      vars:
        tempest_install_method: distro
        tempest_cloud_name: 'overcloud'
      when: use_os_tempest | default(true)
  environment:
    # Disable ssl waarnings
    CURL_CA_BUNDLE: ""
  tags:
    - overcloud-validate

- name: Kill netstat
  hosts: overcloud
  vars:
    kill_netstat: true
  roles:
    - overcloud-network-discovery
  tags:
    - overcloud-validate

- name: Delete the overcloud
  hosts: undercloud
  tags:
    - overcloud-delete
  gather_facts: false
  roles:
    - {role: overcloud-delete,
       when: step_delete_overcloud|default(false)|bool}
