---

- name: Add the virthost to the inventory
  hosts: localhost
  tasks:
    - name: Add virthost
      add_host:
        name: "{{ virthost }}"
        groups: "virthost"
        ansible_fqdn: "{{ virthost }}"
        ansible_user: "root"
        ansible_host: "{{ virthost }}"
  tags:
    - provision

- name: Inventory the virthost
  hosts: localhost
  gather_facts: true
  roles:
    - tripleo-inventory
  tags:
    - provision

- include: teardown.yml

- include: provision.yml

- name: Build test packages using DLRN
  hosts: virthost
  roles:
    - build-test-packages
