---
# This is the playbook used by the `quickstart.sh` script.

- import_playbook: quickstart-extras.yml

- name: Collect logs, create docs, publish
  hosts: all:!localhost
  gather_facts: false
  roles:
    - {role: tripleo-collect-logs, artcl_collect: true}

- name: test overcloud deletion
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: overcloud-delete}
