---
- name: Add the overcloud nodes to the generated inventory
  hosts: undercloud
  gather_facts: true
  tags:
    - standalone
  vars:
    inventory: multinode
  roles:
    - tripleo-inventory

- name: Prepare the undercloud for installation
  hosts: undercloud
  roles:
    - undercloud-setup
  tags:
    - standalone

- name: Run DLRN gate role and install repo
  hosts: undercloud
  vars:
    artg_compressed_gating_repo: "${HOME}/gating_repo.tar.gz"
  roles:
    - build-test-packages
    - {role: install-built-repo, when: compressed_gating_repo is defined}
  tags:
    - build

- name: Set Virtualization Type
  hosts: undercloud
  roles:
    - set-libvirt-type
  tags:
    - standalone

- name: Deploy Standalone
  hosts: undercloud
  vars:
    standalone_libvirt_type: "{{ virt_type|default('qemu') }}"
  roles:
    - standalone
  tags:
    - standalone

- name: Validate the undercloud
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: validate-tempest, when: run_tempest|bool}
  tags:
    - standalone
