---
- name: setup dstat performance monitoring
  hosts: overcloud
  tags:
    - overcloud-validate
  roles:
    - {role: validate-perf,
       when: validate_performance|bool and run_tempest|bool}
  ignore_errors: true

# Validate the deployment
- name: validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
    - undercloud-validate
  gather_facts: false
  roles:
    - {role: validate-simple, when: test_ping|bool}
    - {role: validate-services, when: validate_services|default(false)|bool}
    - {role: validate-tempest, when: run_tempest|bool}

- name: Validate the deployment
  hosts: undercloud
  # Note(chkumar246): Moved the os_tempest related var at the top
  # of play level in order to have scope for the whole of the play
  # https://bugs.launchpad.net/tripleo/+bug/1838496
  vars:
    tempest_install_method: distro
    tempest_cloud_name: 'overcloud'
    tempest_cidr: '192.168.24.0/24'
  tasks:
    - include_tasks: tempest.yml
      when:
        - not run_tempest|bool
        - use_os_tempest is defined
        - use_os_tempest|bool
  tags:
    - overcloud-validate
