---
# TODO(aschultz): fix tags in here to be undercloud-minion-setup
- name: Collect output from undercloud
  hosts: undercloud
  gather_facts: false
  tasks:
    - name: Copy output files
      include_role:
        name: undercloud-deploy
        tasks_from: gather-outputs
  tags:
    - undercloud-setup

- name: Write output from undercloud
  hosts: overcloud
  gather_facts: false
  tasks:
    - name: Reading and setting undercloud facts from gather-outputs
      set_fact:
        undercloud_outputs: "{{ hostvars['undercloud']['undercloud_outputs'] }}"
        undercloud_passwords: "{{ hostvars['undercloud']['undercloud_passwords'] }}"
    - name: write output files
      include_role:
        name: undercloud-setup
        tasks_from: write-outputs
  tags:
    - undercloud-setup

- name: Setup the undercloud minion
  hosts: overcloud
  tasks:
    - name: Include atop setup
      include_role:
        name: undercloud-setup
        tasks_from: atop
    - name: Set container update fact from undercloud
      set_fact:
        update_containers_append_tag: "{{ hostvars['undercloud']['update_containers_append_tag'] | default('') }}"
    - name: Include repo-setup
      include_role:
        name: repo-setup
    - name: Include package installs
      include_role:
        name: undercloud-setup
        tasks_from: package_installs
      when: package_installs|default(true)|bool
    - name: Update built packages
      shell: "{{ ansible_pkg_mgr }} --enablerepo='gating-repo' update -y"
      become: true
      when: hostvars['undercloud']['compressed_gating_repo'] is defined
    - name: Include hostname tasks
      include_role:
        name: undercloud-setup
        tasks_from: hostname
      when: hostname_correction|default(false)|bool or step_set_undercloud_hostname|default(false)|bool
  tags:
    - undercloud-setup

- name: Deploy the undercloud minion
  hosts: overcloud
  roles:
    - undercloud-minion-deploy
  tags:
    - undercloud-setup
