---
- name: Add the overcloud nodes to the generated inventory
  hosts: undercloud
  gather_facts: true
  tags:
    - standalone
  vars:
    inventory: multinode
  roles:
    - tripleo-inventory

- name: Prepare the undercloud for installation
  hosts: undercloud
  roles:
    - undercloud-setup
  tags:
    - standalone

- name: Run DLRN gate role and install repo
  hosts: undercloud
  vars:
    artg_compressed_gating_repo: "${HOME}/gating_repo.tar.gz"
  roles:
    - build-test-packages
    - {role: install-built-repo, when: compressed_gating_repo is defined}
  tags:
    - build

# NOTE(aschultz): nested virt causes problems in CI so we default to qemu
# and do not do the dynamic virt lookup.
- name: Deploy Standalone
  hosts: undercloud
  vars:
    standalone_libvirt_type: "{{ standalone_virt_type|default('qemu') }}"
  roles:
    - standalone
  tags:
    - standalone

- name: Validate the undercloud
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: validate-tempest, when: run_tempest|bool}
  tags:
    - standalone

- name: Validate the deployment
  hosts: undercloud
  tasks:
    - include_role:
        name: os_tempest
      vars:
        ansible_become: true
        tempest_run: 'yes'
        debug: true
        tempest_install_method: distro
        tempest_use_tempestconf: true
        tempest_service_setup_host: '{{ inventory_hostname }}'
        tempest_image_dir: '/home/zuul/images'
        tempest_cloud_name: 'standalone'
        tempest_service_available_cinder: true
        tempest_service_available_neutron: true
        tempest_service_available_swift: true
        tempest_service_available_glance: true
        tempest_service_available_horizon: true
        tempest_service_available_nova: true
        keystone_service_internaluri_insecure: false
        tempest_public_net_physical_type: 'datacentre'
        tempest_public_subnet_cidr: '{{ tempest_cidr }}'
        tempest_public_subnet_gateway_ip: '{{ tempest_cidr|nthhost(1) }}'
        tempest_public_subnet_allocation_pools: '{{ tempest_cidr|nthhost(100) ~ "-" ~ tempest_cidr|nthhost(120) }}'
        tempest_workspace: '/home/zuul/tempest'
        stackviz_venv_bin: "/home/zuul/stackviz_venv/bin"
      when:
        - not run_tempest|bool
        - use_os_tempest is defined
        - use_os_tempest|bool
  tags:
    - standalone
