# This is the playbook used by the `quickstart.sh` script.

- include: quickstart.yml
- include: quickstart-extras-undercloud.yml
- include: quickstart-extras-overcloud-prep.yml
- include: quickstart-extras-overcloud.yml
- include: quickstart-extras-validate.yml
