# Validate the deployment
- name:  validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-simple, when: test_ping|bool }

# Execute tempest against the overcloud deployment
- name:  Execute tempest against the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-tempest, when: tempest_config|bool or run_tempest|bool }

# Execute simple TripleO-UI validations
- name:  Execute simple TripleO-UI validations
  hosts: localhost
  tags:
    - tripleoui-validate
  gather_facts: yes
  roles:
    - { role: validate-ui, when: validate_ui_simple|bool and undercloud_enable_ui|default(true)|bool }
