---
- name: Execute pre undercloud validations
  hosts: undercloud
  gather_facts: true
  tags:
    - component-validations
    - tripleo-validations
  tasks:
    - include_role:
        name: tripleo_validations
      when:
        - job.enable_validation|default(false)|bool
        - release not in ['queens', 'stein']
