working_dir: /home/stack

non_root_user: stack
undercloud_key: "{{ local_working_dir }}/id_rsa_undercloud"

baremetal_provisioning_log: "{{ local_working_dir }}/baremetal_provision.log"

undercloud_local_interface: eth1
undercloud_network_cidr: 192.0.2.0/24

step_provide_undercloud: true
step_prepare_undercloud: true
