---
# tasks file for all_in_one upgrade
- name: gather facts used by role
  setup:
    gather_subset: "!min,pkg_mgr"
  when: ansible_pkg_mgr is not defined

# standalone params
- name: Create the standalone params for upgrade
  template:
    src: "{{ standalone_config }}"
    dest: "{{ working_dir }}/standalone_parameters_upgrade.yaml"
    mode: 0755

- name: Create container parameters script for upgrade
  template:
    src: "{{ standalone_container_prep_script }}"
    dest: "{{ working_dir }}/standalone-container-prep-upgrade.sh"
    mode: "0755"

- name: Run container prepare for upgrade
  shell: >
    set -o pipefail &&
    {{ working_dir }}/standalone-container-prep-upgrade.sh 2>&1 {{ timestamper_cmd }} > {{ working_dir }}/{{ standalone_container_prep_log }}
  changed_when: true

- name: Check whether control plane defaults to HA
  set_fact:
    standalone_upgrade_ha_control_plane: "{{ release not in ['newton', 'ocata', 'pike', 'queens', 'stein', 'train'] }}"

- name: Create the upgrade command for standalone
  template:
    src: "{{ standalone_upgrade_script }}"
    dest: "{{ working_dir }}/standalone-upgrade.sh"
    mode: 0755
  vars:
    standalone_upgrade_control_virtual_ip: >-
      {% if standalone_control_virtual_ip is not defined and standalone_upgrade_ha_control_plane|default(false)|bool -%}
      {{ standalone_ha_control_virtual_ip|default() }}
      {%- else -%}
      {{ standalone_control_virtual_ip|default() }}
      {%- endif -%}

# TODO: (rlandy) remove workaround for LP bug #1953326
- name: Downgrade pcs version
  when:
    - release is defined
    - release in ['ussuri', 'victoria']
  block:
    - name: Downgrade pcs
      shell: |
        dnf downgrade pcs -y;
        rpm -qa | grep pcs
      become: true
      register: downgrade_result

    - name: Return current pcs version
      debug:
        msg: "{{ downgrade_result.stdout }}"

    - name: Ensure the version is not upgraded again
      become: true
      lineinfile:
        path: /etc/dnf/dnf.conf
        state: present
        line: 'exclude=pcs'

- name: Upgrade the standalone
  shell: >
    set -o pipefail &&
    {{ working_dir }}/standalone-upgrade.sh 2>&1 {{ timestamper_cmd }} > {{ working_dir }}/{{ standalone_upgrade_log }}
  changed_when: true
