---

build_repo_dir: "{{ ansible_user_dir }}"

artg_dlrn_repo_url: "https://github.com/openstack-packages/DLRN.git"
artg_rdoinfo_repo_url: "https://github.com/redhat-openstack/rdoinfo"
artg_compressed_gating_repo: "/home/stack/gating_repo.tar.gz"
artg_build_one: true
artg_rdo_packages: []
dlrn_target: >-
  {%- if (ansible_distribution == "RedHat") and
  (dlrn_use_local_mirrors|bool) -%}
  redhat-local
  {%- elif (ansible_distribution == "RedHat") -%}
  redhat
  {%- elif (ansible_distribution == "CentOS") and
  (ansible_distribution_major_version|int >= 8) and
  (dlrn_use_local_mirrors|bool) -%}
  centos8-local
  {%- elif (ansible_distribution == "CentOS") and
  (ansible_distribution_major_version|int >= 8) -%}
  centos8
  {%- elif (ansible_distribution == "CentOS") and
  (ansible_distribution_major_version|int <= 7) and
  (dlrn_use_local_mirrors|bool) -%}
  centos-local
  {%- else -%}
  centos
  {%- endif -%}

initial_dlrn_config: >-
  {%- if (ansible_distribution == "RedHat") -%}
  redhat
  {%- elif (ansible_distribution == "CentOS") and
  (ansible_distribution_major_version|int >= 8) -%}
  centos8
  {%- else -%}
  centos
  {%- endif -%}


dlrn_cleanup: false
dlrn_baseurl: >-
  {%- if ansible_distribution == "RedHat" and ansible_distribution_major_version|int == 8 -%}
  https://trunk.rdoproject.org/rhel8-master
  {%- elif (ansible_distribution == "CentOS") and (ansible_distribution_major_version|int >= 8) -%}
  https://trunk.rdoproject.org/centos8/
  {%- else -%}
  https://trunk.rdoproject.org/centos7/
  {%- endif -%}

use_components: >-
  {%- if (ansible_distribution == "CentOS") and (ansible_distribution_major_version|int >= 8) -%}
  1
  {%- else -%}
  0
  {%- endif -%}

dlrn_use_local_mirrors: false
dlrn_pre_installed: false

artg_skipped_projects:
  - openstack/puppet-openstack-integration
  - openstack/puppet-watcher
  - openstack/tripleo-quickstart
  - openstack/tripleo-quickstart-extras
  - openstack/tripleo-upgrade
  - x/browbeat
  - openstack/tripleo-ha-utils
  - openstack/grenade
  - openstack/project-config
  - openstack/tripleo-ci
  - zuul/zuul-jobs
  - openstack/openstack-virtual-baremetal
  - openstack/openstack-ansible-os_tempest
  - openstack/ansible-role-python_venv_build
  - openstack/ansible-config_template
  - openstack/ansible-role-collect-logs
  - openstack/tripleo-ci-internal-jobs
  - openstack/tripleo-ci-internal-config
  - tripleo-environments
  - openstack/validations-common
  - openstack/validations-libs
