---

artg_dlrn_repo_url: "https://github.com/openstack-packages/DLRN.git"
artg_rdoinfo_repo_url: "https://github.com/redhat-openstack/rdoinfo"
artg_compressed_gating_repo: "/home/stack/gating_repo.tar.gz"
dlrn_cleanup: false

artg_skipped_projects:
  - openstack/tripleo-quickstart
  - openstack/tripleo-quickstart-extras
  - openstack-infra/tripleo-ci
