---
- include: pre-undercloud.yml
  when: step_pre_undercloud_upgrade
  tags:
    - pre-upgrade-undercloud

- include: upgrade-undercloud.yml
  when: step_upgrade_undercloud
  tags:
    - upgrade-undercloud

- include: pre-overcloud.yml
  when: step_pre_overcloud_upgrade
  tags:
    - pre-upgrade-overcloud

- include: upgrade-overcloud.yml
  when: step_upgrade_overcloud
  tags:
    - upgrade-overcloud

- include: post-upgrade.yml
  tags:
    - upgrade-post-tasks
